// scripts/fix-vapor-vitest-bridge-and-boundary.mjs
// 用法：node scripts/fix-vapor-vitest-bridge-and-boundary.mjs
//
// 作用：
// 1. 生成 Vitest 专用 Vue bridge，避免 test-utils CJS runtime 与 vapor browser runtime 打架。
// 2. vitest.config.ts 的 /^vue$/ alias 改到 bridge。
// 3. 测试 setup 自动安装 vaporInteropPlugin。
// 4. 按当前失败日志，把不适合 Vapor 的复杂容器组件退出 vapor。
// 5. 不改 package.json，不回退 Vue 版本，不禁用整个 Vapor 实验。

import { createRequire } from 'node:module';
import { existsSync, mkdirSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const repoRoot = process.cwd();

const vitestConfigPath = resolve(repoRoot, 'vitest.config.ts');
const setupPath = resolve(repoRoot, 'src/__tests__/setup.ts');
const bridgePath = resolve(repoRoot, 'src/__tests__/vue-vapor-vitest-runtime.mjs');
const typeAugmentPath = resolve(repoRoot, 'src/types/vue-vapor.d.ts');

const vueCjsPath = resolve(repoRoot, 'node_modules/vue/dist/vue.cjs.js');
const vaporRuntimePath = resolve(
  repoRoot,
  'node_modules/vue/dist/vue.runtime-with-vapor.esm-browser.js',
);

const assertExists = (path, label) => {
  if (!existsSync(path)) {
    throw new Error(`${label} 不存在：${path}`);
  }
};

const isIdentifier = (key) => /^[$A-Z_a-z][$\w]*$/.test(key);

const writeBridge = async () => {
  assertExists(vueCjsPath, 'vue.cjs.js');
  assertExists(vaporRuntimePath, 'vue.runtime-with-vapor.esm-browser.js');

  const vueCjs = require(vueCjsPath);
  const vueExportKeys = Object.keys(vueCjs)
    .filter(isIdentifier)
    .filter((key) => key !== 'default')
    .filter(
      (key) =>
        ![
          'defineVaporComponent',
          'defineVaporAsyncComponent',
          'createVaporApp',
          'createVaporSSRApp',
          'vaporInteropPlugin',
        ].includes(key),
    )
    .sort();

  const lines = [
    `// Auto-generated by scripts/fix-vapor-vitest-bridge-and-boundary.mjs`,
    `// Vitest 专用：普通 Vue API 走 CJS runtime，Vapor-only API 走 with-vapor runtime。`,
    `// 目的：避免 @vue/test-utils 使用 CJS renderer 时，useAttrs/useSlots 从 browser runtime 取不到 current instance。`,
    ``,
    `import vueCjs from '../../node_modules/vue/dist/vue.cjs.js';`,
    `import * as vaporRuntime from '../../node_modules/vue/dist/vue.runtime-with-vapor.esm-browser.js';`,
    ``,
    `const vdom = vueCjs;`,
    ``,
    ...vueExportKeys.map((key) => `export const ${key} = vdom.${key};`),
    ``,
    `export const defineVaporComponent = vaporRuntime.defineVaporComponent;`,
    `export const defineVaporAsyncComponent = vaporRuntime.defineVaporAsyncComponent;`,
    `export const createVaporApp = vaporRuntime.createVaporApp;`,
    `export const vaporInteropPlugin = vaporRuntime.vaporInteropPlugin;`,
    ``,
    `export default vdom;`,
    ``,
  ];

  mkdirSync(dirname(bridgePath), { recursive: true });
  await writeFile(bridgePath, lines.join('\n'), 'utf8');

  console.log(`bridge written: src/__tests__/vue-vapor-vitest-runtime.mjs`);
};

const writeTypeAugment = async () => {
  const content = `// Auto-generated by scripts/fix-vapor-vitest-bridge-and-boundary.mjs
// Vue 3.6 beta Vapor runtime exports used by local experiment.

import type { App, Plugin } from 'vue';

declare module 'vue' {
  export const defineVaporComponent: (...args: unknown[]) => unknown;
  export const defineVaporAsyncComponent: (...args: unknown[]) => unknown;
  export const createVaporApp: (...args: unknown[]) => App;
  export const vaporInteropPlugin: Plugin;
}
`;

  mkdirSync(dirname(typeAugmentPath), { recursive: true });
  await writeFile(typeAugmentPath, content, 'utf8');

  console.log(`types written: src/types/vue-vapor.d.ts`);
};

const replaceSectionBetween = (content, startNeedle, endNeedle, replacement, label) => {
  const start = content.indexOf(startNeedle);

  if (start === -1) {
    throw new Error(`${label}: 找不到起始标记 ${JSON.stringify(startNeedle)}`);
  }

  const end = content.indexOf(endNeedle, start);

  if (end === -1) {
    throw new Error(`${label}: 找不到结束标记 ${JSON.stringify(endNeedle)}`);
  }

  return `${content.slice(0, start)}${replacement}${content.slice(end)}`;
};

const patchVitestConfig = async () => {
  assertExists(vitestConfigPath, 'vitest.config.ts');

  const original = await readFile(vitestConfigPath, 'utf8');

  const resolveBlock = `
  resolve: {
    alias: [
      {
        find: /^vue$/,
        replacement: path.resolve(__dirname, 'src/__tests__/vue-vapor-vitest-runtime.mjs'),
      },
      {
        find: '@',
        replacement: path.resolve(__dirname, 'src'),
      },
    ],
  },`;

  const next = replaceSectionBetween(original, '\n  resolve:', '\n  test:', resolveBlock, 'vitest.config.ts');

  if (next !== original) {
    await writeFile(vitestConfigPath, next, 'utf8');
    console.log('patched: vitest.config.ts');
  } else {
    console.log('unchanged: vitest.config.ts');
  }
};

const patchSetup = async () => {
  assertExists(setupPath, 'src/__tests__/setup.ts');

  const original = await readFile(setupPath, 'utf8');
  let next = original;

  if (!next.includes("import { config } from '@vue/test-utils';")) {
    next = next.replace(
      "import { beforeEach, vi } from 'vitest';",
      "import { config } from '@vue/test-utils';\nimport { beforeEach, vi } from 'vitest';\nimport { vaporInteropPlugin } from 'vue';",
    );
  }

  if (!next.includes('vaporInteropPlugin-installed-for-vitest')) {
    next = next.replace(
      "import { vaporInteropPlugin } from 'vue';",
      "import { vaporInteropPlugin } from 'vue';\n\n// vaporInteropPlugin-installed-for-vitest\nconfig.global.plugins = config.global.plugins ?? [];\nif (!config.global.plugins.includes(vaporInteropPlugin)) {\n  config.global.plugins.push(vaporInteropPlugin);\n}",
    );
  }

  if (next !== original) {
    await writeFile(setupPath, next, 'utf8');
    console.log('patched: src/__tests__/setup.ts');
  } else {
    console.log('unchanged: src/__tests__/setup.ts');
  }
};

const removeInjectedEmptyVaporScript = (content) =>
  content.replace(
    /^<script\s+setup\s+vapor\s+lang=(["'])ts\1>\s*<\/script>\s*\r?\n\r?\n/i,
    '',
  );

const removeVaporFromScriptTags = (content) =>
  content.replace(/<script\b[^>]*>/gi, (tag) => {
    if (!/\bvapor\b/.test(tag)) {
      return tag;
    }

    return tag.replace(/\s+vapor(?=[\s>])/g, '').replace(/\s+>/g, '>');
  });

const removeVaporFromFile = async (relativePath) => {
  const absolutePath = resolve(repoRoot, relativePath);

  if (!existsSync(absolutePath)) {
    console.log(`missing: ${relativePath}`);
    return false;
  }

  const original = await readFile(absolutePath, 'utf8');

  let next = original;
  next = removeInjectedEmptyVaporScript(next);
  next = removeVaporFromScriptTags(next);

  if (next === original) {
    console.log(`unchanged: ${relativePath}`);
    return false;
  }

  await writeFile(absolutePath, next, 'utf8');
  console.log(`removed vapor: ${relativePath}`);
  return true;
};

// 当前这批失败里属于复杂容器 / slot / provide-inject / useAttrs-useSlots / contenteditable / teleport / markdown renderer。
// 这些先退出 Vapor，保留 Vapor runtime 给更简单的叶子组件继续实验。
const incompatibleVaporFiles = [
  'src/components/ai-elements/shimmer/Shimmer.vue',

  'src/components/ai-elements/code-block/CodeBlock.vue',
  'src/components/ai-elements/code-block/CodeBlockContainer.vue',
  'src/components/ai-elements/code-block/CodeBlockContent.vue',
  'src/components/ai-elements/code-block/CodeBlockCopyButton.vue',

  'src/components/business/ai/chat/AiChatThread.vue',
  'src/components/business/ai/chat/AiMarkdown.vue',
  'src/components/business/ai/chat/AiMarkdownCodeBlock.vue',
  'src/components/business/ai/chat/AiPromptInput.vue',

  'src/components/business/ai/edit/AiChangedFilesSummary.vue',
  'src/components/business/ai/edit/AiDiffHunkViewer.vue',
  'src/components/business/ai/edit/AiDiffPreviewEditor.vue',

  'src/components/business/ai/provider/AiProviderSettings.vue',

  'src/components/business/ai/shell/AiAssistantPanel.vue',
  'src/components/business/ai/shell/AiWebPreviewSidebar.vue',
  'src/components/business/ai/shell/AiWorkspaceSurface.vue',

  'src/components/business/ai/web/AiWebSourcesPanel.vue',

  'src/components/business/ai/thread/AiThreadReasoning.vue',

  'src/components/business/ai/skill/AiSlashCommandMenu.vue',

  'src/components/workbench/sidebar/explorer/WorkspaceExplorerPanel.vue',
];

const patchVaporBoundary = async () => {
  let changedCount = 0;

  for (const file of incompatibleVaporFiles) {
    if (await removeVaporFromFile(file)) {
      changedCount += 1;
    }
  }

  console.log(`vapor boundary patched files: ${changedCount}`);
};

const main = async () => {
  await writeBridge();
  await writeTypeAugment();
  await patchVitestConfig();
  await patchSetup();
  await patchVaporBoundary();

  console.log('\n下一步清缓存并验证：');
  console.log('Remove-Item -Recurse -Force node_modules/.vite -ErrorAction SilentlyContinue');
  console.log('pnpm test');
  console.log('pnpm typecheck');
  console.log('pnpm build');

  console.log('\n说明：');
  console.log('- Vite dev/build 仍可继续用 vue.runtime-with-vapor.esm-browser.js。');
  console.log('- Vitest 走 bridge，避免 test-utils 的 CJS renderer 和 browser vapor runtime 双实例冲突。');
  console.log('- 这不是关闭真 Vapor，而是把复杂容器退出 Vapor，保留可验证的 Vapor 边界。');
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});