// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	detectExecutionEnvironment: () => __TAURI_INVOKE<ExecutionEnvironment>("detect_execution_environment"),
	applyWorkspaceReplacement: (payload: WorkspaceReplacementApplyRequest) => __TAURI_INVOKE<WorkspaceReplacementApplyPayload>("apply_workspace_replacement", { payload }),
	previewWorkspaceReplacement: (payload: WorkspaceReplacementRequest) => __TAURI_INVOKE<WorkspaceReplacementPreviewPayload>("preview_workspace_replacement", { payload }),
	searchWorkspace: (payload: WorkspaceSearchRequest) => __TAURI_INVOKE<WorkspaceSearchPayload>("search_workspace", { payload }),
	analyzeScript: (payload: AnalyzeScriptRequest) => __TAURI_INVOKE<AnalyzeScriptPayload>("analyze_script", { payload }),
	formatScript: (payload: FormatScriptRequest) => __TAURI_INVOKE<FormatScriptPayload>("format_script", { payload }),
	formatDocument: (payload: FormatDocumentRequest) => __TAURI_INVOKE<FormatDocumentPayload>("format_document", { payload }),
	listSkills: () => __TAURI_INVOKE<SkillListPayload>("list_skills"),
	readSkill: (slug: string) => __TAURI_INVOKE<SkillDetailPayload>("read_skill", { slug }),
	saveSkill: (payload: SaveSkillRequest) => __TAURI_INVOKE<SkillDetailPayload>("save_skill", { payload }),
	deleteSkill: (payload: DeleteSkillRequest) => __TAURI_INVOKE<DeleteSkillPayload>("delete_skill", { payload }),
	applyWindowStage: (stage: WindowStage) => __TAURI_INVOKE<null>("apply_window_stage", { stage }),
	setWindowBackground: (input: SetWindowBackgroundInput, traceId: string | null) => __TAURI_INVOKE<null>("set_window_background", { input, traceId }),
	createWorkspacePath: (payload: WorkspacePathCreateRequest) => __TAURI_INVOKE<WorkspacePathCreatePayload>("create_workspace_path", { payload }),
	deleteWorkspacePath: (payload: WorkspacePathDeleteRequest) => __TAURI_INVOKE<WorkspacePathDeletePayload>("delete_workspace_path", { payload }),
	listWorkspaceEntries: (path: string | null, rootPath: string | null) => __TAURI_INVOKE<WorkspaceDirectoryPayload>("list_workspace_entries", { path, rootPath }),
	loadImageAsset: (path: string) => __TAURI_INVOKE<ImageAssetPayload>("load_image_asset", { path }),
	loadScript: (path: string, workspaceRootPath: string | null) => __TAURI_INVOKE<ScriptFilePayload>("load_script", { path, workspaceRootPath }),
	renameWorkspacePath: (payload: WorkspacePathRenameRequest) => __TAURI_INVOKE<WorkspacePathRenamePayload>("rename_workspace_path", { payload }),
	saveScript: (payload: SaveScriptRequest) => __TAURI_INVOKE<ScriptFilePayload>("save_script", { payload }),
	/**
	 *  启动（或重启）工作区文件监听
	 * 
	 *  真正的目录遍历与监听在后台线程完成，本命令仅做根目录校验与 watcher 构造后
	 *  立即返回，因此打开超大仓库也不会阻塞前端。监听结果通过 `WorkspaceFsEvent` 推送。
	 *  若已有监听，会先换入新句柄再通知旧线程退出，旧 watcher 在其线程结束时 Drop。
	 * 
	 *  # 参数
	 *  - `root_path`: 工作区根目录的绝对或相对路径，会被 canonicalize
	 * 
	 *  # 错误
	 *  路径不存在 / 不是目录、或 watcher 构造失败时返回 `Err(String)`。
	 *  注意：后台的实际 watch 调用失败只记日志，不再同步抛出（后台化的取舍）。
	 */
	startWorkspaceWatching: (rootPath: string) => __TAURI_INVOKE<null>("start_workspace_watching", { rootPath }),
	/**
	 *  停止工作区文件监听
	 * 
	 *  通知后台线程退出；线程在 `DEBOUNCE_DURATION` 内跳出循环并 Drop watcher。
	 *  重复调用、未启动时调用都是安全的（幂等）。
	 */
	stopWorkspaceWatching: () => __TAURI_INVOKE<null>("stop_workspace_watching"),
	ensureTerminalSession: (payload: EnsureTerminalSessionRequest) => __TAURI_INVOKE<TerminalSessionPayload>("ensure_terminal_session", { payload }),
	writeTerminalInput: (payload: TerminalInputRequest) => __TAURI_INVOKE<null>("write_terminal_input", { payload }),
	resizeTerminalSession: (payload: TerminalResizeRequest) => __TAURI_INVOKE<null>("resize_terminal_session", { payload }),
	closeTerminalSession: (payload: CloseTerminalSessionRequest) => __TAURI_INVOKE<null>("close_terminal_session", { payload }),
	dispatchScriptToTerminal: (payload: DispatchTerminalScriptRequest) => __TAURI_INVOKE<DispatchTerminalScriptPayload>("dispatch_script_to_terminal", { payload }),
	cancelTerminalRun: (payload: CancelTerminalRunRequest) => __TAURI_INVOKE<null>("cancel_terminal_run", { payload }),
	listGitBranches: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitBranchListPayload>("list_git_branches", { payload }),
	checkoutGitBranch: (payload: GitBranchCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_branch", { payload }),
	/**
	 *  以分离 HEAD 方式检出指定提交（等价 `git checkout <commit>`）。
	 *  复用分支切换的工作区 / 索引 / HEAD 同步实现；要求工作区干净。
	 */
	checkoutGitCommit: (payload: GitCommitCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_commit", { payload }),
	createGitBranch: (payload: GitBranchCreateRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("create_git_branch", { payload }),
	getGitDiffPreview: (payload: GitDiffPreviewRequest) => __TAURI_INVOKE<GitDiffPreviewPayload>("get_git_diff_preview", { payload }),
	/**  返回特定提交中单个文件的 diff（对比父提交）。 */
	getGitCommitFileDiff: (payload: GitCommitFileDiffRequest) => __TAURI_INVOKE<GitCommitFileDiffPayload>("get_git_commit_file_diff", { payload }),
	/**
	 *  返回特定提交中单个文件的主界面 Diff 预览（对比父提交）。
	 *  复用与工作区/暂存区 Diff 相同的只读 Diff 视图（GitDiffViewer / openGitDiffDocument）。
	 */
	getGitCommitFileDiffPreview: (payload: GitCommitFileDiffRequest) => __TAURI_INVOKE<GitDiffPreviewPayload>("get_git_commit_file_diff_preview", { payload }),
	getGithubAuthStatus: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("get_github_auth_status", { payload }),
	beginGithubDeviceAuth: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubDeviceAuthPayload>("begin_github_device_auth", { payload }),
	completeGithubDeviceAuth: (payload: GitHubDeviceAuthCompleteRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("complete_github_device_auth", { payload }),
	connectGithub: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("connect_github", { payload }),
	disconnectGithub: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("disconnect_github", { payload }),
	listGitCommitHistory: (payload: GitCommitHistoryRequest) => __TAURI_INVOKE<GitCommitHistoryPayload>("list_git_commit_history", { payload }),
	/**
	 *  读取单个提交的详细信息（用于历史悬浮卡片）：提交元数据 + 相对首个父提交的
	 *  文件/行变更聚合（文件数、插入、删除）。根提交对空树取差异。
	 */
	getGitCommitDetail: (payload: GitCommitDetailRequest) => __TAURI_INVOKE<GitCommitDetailPayload>("get_git_commit_detail", { payload }),
	getGitPullRequestSupport: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("get_git_pull_request_support", { payload }),
	setGitRemote: (payload: GitRemoteSetRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("set_git_remote", { payload }),
	listGitPullRequests: (payload: GitPullRequestListRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload[]>("list_git_pull_requests", { payload }),
	getGitPullRequestDetail: (payload: GitPullRequestDetailRequest) => __TAURI_INVOKE<GitPullRequestDetailPayload>("get_git_pull_request_detail", { payload }),
	createGitPullRequest: (payload: GitPullRequestCreateRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("create_git_pull_request", { payload }),
	mergeGitPullRequest: (payload: GitPullRequestMergeRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("merge_git_pull_request", { payload }),
	closeGitPullRequest: (payload: GitPullRequestCloseRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("close_git_pull_request", { payload }),
	/**
	 *  回滚指定提交：把该提交的改动反向应用到工作区与索引（等价 `git revert --no-commit`）。
	 *  要求工作区干净；结果以「已暂存」状态呈现，用户检查后可直接提交。
	 */
	revertGitCommit: (payload: GitCommitRevertRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("revert_git_commit", { payload }),
	listGitStashes: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitStashListPayload>("list_git_stashes", { payload }),
	saveGitStash: (payload: GitStashSaveRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("save_git_stash", { payload }),
	applyGitStash: (payload: GitStashApplyRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("apply_git_stash", { payload }),
	dropGitStash: (payload: GitStashDropRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("drop_git_stash", { payload }),
	getGitRepositoryStatus: (workspaceRootPath: string | null) => __TAURI_INVOKE<GitRepositoryStatusPayload>("get_git_repository_status", { workspaceRootPath }),
	initGitRepository: (workspaceRootPath: string | null) => __TAURI_INVOKE<GitRepositoryStatusPayload>("init_git_repository", { workspaceRootPath }),
	getGitFileBaseline: (path: string) => __TAURI_INVOKE<GitFileBaselinePayload>("get_git_file_baseline", { path }),
	stageGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("stage_git_paths", { payload }),
	unstageGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("unstage_git_paths", { payload }),
	commitGitIndex: (payload: GitCommitRequest) => __TAURI_INVOKE<GitCommitResultPayload>("commit_git_index", { payload }),
	discardGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("discard_git_paths", { payload }),
	testSshConnection: (payload: SshConnectionTestRequest) => __TAURI_INVOKE<SshConnectionTestPayload>("test_ssh_connection", { payload }),
	trustSshHostKey: (host: string, port: number) => __TAURI_INVOKE<SshHostKeyTrustPayload>("trust_ssh_host_key", { host, port }),
	saveSshPassword: (payload: SshPasswordSaveRequest) => __TAURI_INVOKE<SshPasswordStatusPayload>("save_ssh_password", { payload }),
	getSshPassword: (payload: SshPasswordGetRequest) => __TAURI_INVOKE<SshPasswordPayload>("get_ssh_password", { payload }),
	listSshConfigHosts: () => __TAURI_INVOKE<SshConfigHostPayload[]>("list_ssh_config_hosts"),
	listSshDirectory: (payload: SshDirectoryListRequest) => __TAURI_INVOKE<SshDirectoryListPayload>("list_ssh_directory", { payload }),
	downloadSshFile: (payload: SshFileDownloadRequest) => __TAURI_INVOKE<SshFileDownloadPayload>("download_ssh_file", { payload }),
	uploadSshFile: (payload: SshFileUploadRequest) => __TAURI_INVOKE<SshFileUploadPayload>("upload_ssh_file", { payload }),
	readSshFile: (payload: SshFileReadRequest) => __TAURI_INVOKE<SshFileReadPayload>("read_ssh_file", { payload }),
	writeSshFile: (payload: SshFileWriteRequest) => __TAURI_INVOKE<SshFileWritePayload>("write_ssh_file", { payload }),
	deleteSshPath: (payload: SshPathDeleteRequest) => __TAURI_INVOKE<SshPathDeletePayload>("delete_ssh_path", { payload }),
	renameSshPath: (payload: SshPathRenameRequest) => __TAURI_INVOKE<SshPathRenamePayload>("rename_ssh_path", { payload }),
	createSshDirectory: (payload: SshDirectoryCreateRequest) => __TAURI_INVOKE<SshDirectoryCreatePayload>("create_ssh_directory", { payload }),
	agentSidecarHealth: () => __TAURI_INVOKE<AgentSidecarHealthPayload>("agent_sidecar_health"),
	agentSidecarRestart: () => __TAURI_INVOKE<AgentSidecarHealthPayload>("agent_sidecar_restart"),
	agentSidecarWarmup: () => __TAURI_INVOKE<AgentSidecarWarmupPayload>("agent_sidecar_warmup"),
	agentSidecarChat: (payload: AgentSidecarChatRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_chat", { payload }),
	agentSidecarResolveApproval: (payload: AgentSidecarApprovalResolveRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_resolve_approval", { payload }),
	agentSidecarRestoreCheckpoint: (payload: AgentSidecarCheckpointRestoreRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_restore_checkpoint", { payload }),
	agentSidecarOrchestrate: (payload: AgentSidecarOrchestrateRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarOrchestratePayload>("agent_sidecar_orchestrate", { payload }),
	agentSidecarOrchestrateResume: (payload: AgentSidecarOrchestrateResumeRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarOrchestratePayload>("agent_sidecar_orchestrate_resume", { payload }),
	/**  Create (or reuse) the child webview and start the CDP control plane. Idempotent. */
	agentWebviewCreate: (input: AgentWebviewCreateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_create", { input, traceId }),
	/**  Sync child webview bounds. */
	agentWebviewSetBounds: (input: AgentWebviewBoundsInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_set_bounds", { input, traceId }),
	/**  Show/hide the child webview. */
	agentWebviewSetVisible: (input: AgentWebviewVisibleInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_set_visible", { input, traceId }),
	/**  Navigate to a new URL (address bar). */
	agentWebviewNavigate: (input: AgentWebviewNavigateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_navigate", { input, traceId }),
	/**  Back one entry (CDP real history). */
	agentWebviewBack: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_back", { traceId }),
	/**  Forward one entry (CDP real history). */
	agentWebviewForward: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_forward", { traceId }),
	/**  Reload current page (CDP Page.reload). */
	agentWebviewReload: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_reload", { traceId }),
	/**
	 *  Enter element-pick mode by injecting the @medv/finder picker. The next element the user
	 *  clicks is captured and surfaced via AgentWebviewElementPickedEvent.
	 */
	agentWebviewStartSelect: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_start_select", { traceId }),
	/**  Exit element-pick mode without picking (tears down the injected picker). */
	agentWebviewCancelSelect: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_cancel_select", { traceId }),
	/**  Open the given URL in the system default browser (official tauri-plugin-opener, Rust-side). */
	agentWebviewOpenExternal: (input: AgentWebviewNavigateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_open_external", { input, traceId }),
	/**  Destroy the child webview and tear down the CDP session. Idempotent. */
	agentWebviewDestroy: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_destroy", { traceId }),
	aiGetConfig: () => __TAURI_INVOKE<AiConfigPayload>("ai_get_config"),
	aiSaveConfig: (payload: AiSaveConfigRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_config", { payload }),
	aiSaveCredentials: (payload: AiSaveCredentialsRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_credentials", { payload }),
	aiTestProviderConfig: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider_config", { payload }),
	aiConnectProvider: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderConnectionPayload>("ai_connect_provider", { payload }),
	aiClearCredentials: () => __TAURI_INVOKE<null>("ai_clear_credentials"),
	aiTestProvider: () => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider"),
	aiGenerateConversationTitle: (payload: AiConversationTitleRequest) => __TAURI_INVOKE<AiConversationTitlePayload>("ai_generate_conversation_title", { payload }),
	aiGetSuggestionPoolCache: () => __TAURI_INVOKE<{
	suggestions: string[],
	model: string,
	generatedAt: string,
} | null>("ai_get_suggestion_pool_cache"),
	aiGenerateSuggestionPool: (payload: AiSuggestionPoolRequest) => __TAURI_INVOKE<AiSuggestionPoolPayload>("ai_generate_suggestion_pool", { payload }),
	aiChatStream: (payload: AiChatRequest) => __TAURI_INVOKE<AiChatStreamPayload>("ai_chat_stream", { payload }),
	aiCancel: (payload: AiCancelRequest) => __TAURI_INVOKE<null>("ai_cancel", { payload }),
	aiInlineComplete: (payload: AiInlineCompletionRequest) => __TAURI_INVOKE<AiInlineCompletionResult>("ai_inline_complete"... : too large}]}                       e, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_cancel_select", { traceId }),
	/**  Open the given URL in the system default browser (official tauri-plugin-opener, Rust-side). */
	agentWebviewOpenExternal: (input: AgentWebviewNavigateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_open_external", { input, traceId }),
	/**  Destroy the child webview and tear down the CDP session. Idempotent. */
	agentWebviewDestroy: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_destroy"),
	aiGetConfig: () => __TAURI_INVOKE<AiConfigPayload>("ai_get_config"),
	aiSaveConfig: (payload: AiSaveConfigRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_config", { payload }),
	aiSaveCredentials: (payload: AiSaveCredentialsRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_credentials", { payload }),
	aiTestProviderConfig: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider_config", { payload }),
	aiConnectProvider: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderConnectionPayload>("ai_connect_provider", { payload }),
	aiClearCredentials: () => __TAURI_INVOKE<null>("ai_clear_credentials"),
	aiTestProvider: () => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider"),
	aiGenerateConversationTitle: (payload: AiConversationTitleRequest) => __TAURI_INVOKE<AiConversationTitlePayload>("ai_generate_conversation_title", { payload }),
	aiGetSuggestionPoolCache: () => __TAURI_INVOKE<{
	suggestions: string[],
	model: string,
	generatedAt: string,
} | null>("ai_get_suggestion_pool_cache"),
	aiGenerateSuggestionPool: (payload: AiSuggestionPoolRequest) => __TAURI_INVOKE<AiSuggestionPoolPayload>("ai_generate_suggestion_pool", { payload }),
	aiChatStream: (payload: AiChatRequest) => __TAURI_INVOKE<AiChatStreamPayload>("ai_chat_stream", { payload }),
	aiCancel: (payload: AiCancelRequest) => __TAURI_INVOKE<null>("ai_cancel", { payload }),
	aiInlineComplete: (payload: AiInlineCompletionRequest) => __TAURI_INVOKE<AiInlineCompletionResult>("ai_inline_complete", { payload }),
	aiAgentClassifyTask: (payload: AiAgentClassifyTaskRequest) => __TAURI_INVOKE<AiAgentClassifyTaskPayload>("ai_agent_classify_task", { payload }),
	aiAgentSetNetworkPermission: (payload: AiAgentSetNetworkPermissionRequest) => __TAURI_INVOKE<AiAgentNetworkPermissionPayload>("ai_agent_set_network_permission", { payload }),
	aiWebSearch: (payload: AiWebSearchInput) => __TAURI_INVOKE<AiWebSearchPayload>("ai_web_search", { payload }),
	aiWebFetch: (payload: AiWebFetchInput) => __TAURI_INVOKE<AiWebFetchPayload>("ai_web_fetch", { payload }),
	aiProposePatch: (payload: AiProposePatchRequest) => __TAURI_INVOKE<AiProposePatchPayload>("ai_propose_patch", { payload }),
	aiApplyPatch: (payload: AiApplyPatchRequest) => __TAURI_INVOKE<AiApplyPatchPayload>("ai_apply_patch", { payload }),
	aiEditGetAuthLevel: () => __TAURI_INVOKE<AiEditAuthStatePayload>("ai_edit_get_auth_level"),
	aiEditSetAuthLevel: (payload: AiEditSetAuthLevelRequest) => __TAURI_INVOKE<AiEditAuthStatePayload>("ai_edit_set_auth_level", { payload }),
	aiEditListTimeline: (payload: AiEditListTimelineRequest) => __TAURI_INVOKE<AiEditListTimelinePayload>("ai_edit_list_timeline", { payload }),
	aiEditSetPin: (payload: AiEditSetPinRequest) => __TAURI_INVOKE<AiEditSetPinPayload>("ai_edit_set_pin", { payload }),
	aiEditGetDiff: (payload: AiEditGetDiffRequest) => __TAURI_INVOKE<AiEditGetDiffPayload>("ai_edit_get_diff", { payload }),
	aiEditCreateSnapshot: (payload: AiEditCreateSnapshotRequest) => __TAURI_INVOKE<AiEditCreateSnapshotPayload>("ai_edit_create_snapshot", { payload }),
	aiEditRestoreSnapshot: (payload: AiEditRestoreSnapshotRequest) => __TAURI_INVOKE<AiEditRestoreSnapshotPayload>("ai_edit_restore_snapshot", { payload }),
	aiEditUndoOperation: (payload: AiEditUndoOperationRequest) => __TAURI_INVOKE<AiEditUndoOperationPayload>("ai_edit_undo_operation", { payload }),
	aiEditRevertFile: (payload: AiEditRevertFileRequest) => __TAURI_INVOKE<AiEditRevertFilePayload>("ai_edit_revert_file", { payload }),
	aiEditRevertHunk: (payload: AiEditRevertHunkRequest) => __TAURI_INVOKE<AiEditRevertHunkPayload>("ai_edit_revert_hunk", { payload }),
	aiEditRevertTask: (payload: AiEditRevertTaskRequest) => __TAURI_INVOKE<AiEditRevertTaskPayload>("ai_edit_revert_task"... : too large}]}                       rface type issue; continue? Need respond done. But need because create_or_update_file content huge maybe tool likely failed/truncated? Actually no output yet? It didn't return? I see from function call input huge maybe invalid? It returned truncated? Wait tool output in commentary after callFunction? It appears a weird tool-? maybe not output? It is in transcript as call, but no distinct output; likely failed due content too large? I sent entire file content but was truncated by system? Need check. The tool call output maybe not shown? Actually after my call, the next tool results are from later parallel calls, so maybe call did not output? Let me scan: I see `functions.callFunction` to create/update, then not output, then parallel calls. Did I accidentally not wait? It should output before next. Maybe it is omitted? In analysis, need verify main commit. Use get_file_contents specific maybe. Also realize I accidentally edited generated file content maybe malformed due huge truncation 