// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	detectExecutionEnvironment: () => __TAURI_INVOKE<ExecutionEnvironment>("detect_execution_environment"),
	applyWorkspaceReplacement: (payload: WorkspaceReplacementApplyRequest) => __TAURI_INVOKE<WorkspaceReplacementApplyPayload>("apply_workspace_replacement", { payload }),
	previewWorkspaceReplacement: (payload: WorkspaceReplacementRequest) => __TAURI_INVOKE<WorkspaceReplacementPreviewPayload>("preview_workspace_replacement", { payload }),
	searchWorkspace: (payload: WorkspaceSearchRequest) => __TAURI_INVOKE<WorkspaceSearchPayload>("search_workspace", { payload }),
	analyzeScript: (payload: AnalyzeScriptRequest) => __TAURI_INVOKE<AnalyzeScriptPayload>("analyze_script", { payload }),
	formatScript: (payload: FormatScriptRequest) => __TAURI_INVOKE<FormatScriptPayload>("format_script", { payload }),
	applyWindowStage: (stage: WindowStage) => __TAURI_INVOKE<null>("apply_window_stage", { stage }),
	setWindowBackground: (input: SetWindowBackgroundInput, traceId: string | null) => __TAURI_INVOKE<null>("set_window_background", { input, traceId }),
	createWorkspacePath: (payload: WorkspacePathCreateRequest) => __TAURI_INVOKE<WorkspacePathCreatePayload>("create_workspace_path", { payload }),
	deleteWorkspacePath: (payload: WorkspacePathDeleteRequest) => __TAURI_INVOKE<WorkspacePathDeletePayload>("delete_workspace_path", { payload }),
	listWorkspaceEntries: (path: string | null, rootPath: string | null) => __TAURI_INVOKE<WorkspaceDirectoryPayload>("list_workspace_entries", { path, rootPath }),
	loadImageAsset: (path: string) => __TAURI_INVOKE<ImageAssetPayload>("load_image_asset", { path }),
	loadScript: (path: string) => __TAURI_INVOKE<ScriptFilePayload>("load_script", { path }),
	renameWorkspacePath: (payload: WorkspacePathRenameRequest) => __TAURI_INVOKE<WorkspacePathRenamePayload>("rename_workspace_path", { payload }),
	saveScript: (payload: SaveScriptRequest) => __TAURI_INVOKE<ScriptFilePayload>("save_script", { payload }),
	/**
	 *  启动（或重启）工作区文件监听
	 * 
	 *  监听结果通过 `WorkspaceFsEvent` 事件推送到前端。
	 *  若已有监听，会先构造新 watcher，成功后原子替换旧的，旧 watcher 在 Drop 中关闭。
	 * 
	 *  # 参数
	 *  - `root_path`: 工作区根目录的绝对或相对路径，会被 canonicalize
	 * 
	 *  # 错误
	 *  路径不存在、不是目录、或底层 watcher 启动失败时返回 `Err(String)`
	 */
	startWorkspaceWatching: (rootPath: string) => __TAURI_INVOKE<null>("start_workspace_watching", { rootPath }),
	/**
	 *  停止工作区文件监听
	 * 
	 *  调用后 watcher 立即被 Drop，回调线程退出。
	 *  重复调用、未启动时调用都是安全的（幂等）。
	 */
	stopWorkspaceWatching: () => __TAURI_INVOKE<null>("stop_workspace_watching"),
	ensureTerminalSession: (payload: EnsureTerminalSessionRequest) => __TAURI_INVOKE<TerminalSessionPayload>("ensure_terminal_session", { payload }),
	writeTerminalInput: (payload: TerminalInputRequest) => __TAURI_INVOKE<null>("write_terminal_input", { payload }),
	resizeTerminalSession: (payload: TerminalResizeRequest) => __TAURI_INVOKE<null>("resize_terminal_session", { payload }),
	closeTerminalSession: (payload: CloseTerminalSessionRequest) => __TAURI_INVOKE<null>("close_terminal_session", { payload }),
	dispatchScriptToTerminal: (payload: DispatchTerminalScriptRequest) => __TAURI_INVOKE<DispatchTerminalScriptPayload>("dispatch_script_to_terminal", { payload }),
	cancelTerminalRun: (payload: CancelTerminalRunRequest) => __TAURI_INVOKE<null>("cancel_terminal_run", { payload }),
	listGitBranches: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitBranchListPayload>("list_git_branches", { payload }),
	checkoutGitBranch: (payload: GitBranchCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_branch", { payload }),
	/**
	 *  以分离 HEAD 方式检出指定提交（等价 `git checkout <commit>`）。
	 *  复用分支切换的工作区 / 索引 / HEAD 同步实现；要求工作区干净。
	 */
	checkoutGitCommit: (payload: GitCommitCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_commit", { payload }),
	createGitBranch: (payload: GitBranchCreateRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("create_git_branch", { payload }),
	getGitDiffPreview: (payload: GitDiffPreviewRequest) => __TAURI_INVOKE<GitDiffPreviewPayload>("get_git_diff_preview", { payload }),
	/**  返回特定提交中单个文件的 diff（对比父提交）。 */
	getGitCommitFileDiff: (payload: GitCommitFileDiffRequest) => __TAURI_INVOKE<GitCommitFileDiffPayload>("get_git_commit_file_diff", { payload }),
	listGitCommitHistory: (payload: GitCommitHistoryRequest) => __TAURI_INVOKE<GitCommitHistoryPayload>("list_git_commit_history", { payload }),
	/**
	 *  读取单个提交的详细信息（用于历史悬浮卡片）：提交元数据 + 相对首个父提交的
	 *  文件/行变更聚合（文件数、插入、删除）。根提交对空树取差异。
	 */
	getGitCommitDetail: (payload: GitCommitDetailRequest) => __TAURI_INVOKE<GitCommitDetailPayload>("get_git_commit_detail", { payload }),
	getGitPullRequestSupport: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("get_git_pull_request_support", { payload }),
	setGitRemote: (payload: GitRemoteSetRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("set_git_remote", { payload }),
	listGitPullRequests: (payload: GitPullRequestListRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload[]>("list_git_pull_requests", { payload }),
	getGitPullRequestDetail: (payload: GitPullRequestDetailRequest) => __TAURI_INVOKE<GitPullRequestDetailPayload>("get_git_pull_request_detail", { payload }),
	createGitPullRequest: (payload: GitPullRequestCreateRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("create_git_pull_request", { payload }),
	mergeGitPullRequest: (payload: GitPullRequestMergeRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("merge_git_pull_request", { payload }),
	closeGitPullRequest: (payload: GitPullRequestCloseRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("close_git_pull_request", { payload }),
	/**
	 *  回滚指定提交：把该提交的改动反向应用到工作区与索引（等价 `git revert --no