// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	detectExecutionEnvironment: () => __TAURI_INVOKE<ExecutionEnvironment>("detect_execution_environment"),
	applyWorkspaceReplacement: (payload: WorkspaceReplacementApplyRequest) => __TAURI_INVOKE<WorkspaceReplacementApplyPayload>("apply_workspace_replacement", { payload }),
	previewWorkspaceReplacement: (payload: WorkspaceReplacementRequest) => __TAURI_INVOKE<WorkspaceReplacementPreviewPayload>("preview_workspace_replacement", { payload }),
	searchWorkspace: (payload: WorkspaceSearchRequest) => __TAURI_INVOKE<WorkspaceSearchPayload>("search_workspace", { payload }),
	analyzeScript: (payload: AnalyzeScriptRequest) => __TAURI_INVOKE<AnalyzeScriptPayload>("analyze_script", { payload }),
	formatScript: (payload: FormatScriptRequest) => __TAURI_INVOKE<FormatScriptPayload>("format_script", { payload }),
	formatDocument: (payload: FormatDocumentRequest) => __TAURI_INVOKE<FormatDocumentPayload>("format_document", { payload }),
	listSkills: () => __TAURI_INVOKE<SkillListPayload>("list_skills"),
	readSkill: (slug: string) => __TAURI_INVOKE<SkillDetailPayload>("read_skill", { slug }),
	saveSkill: (payload: SaveSkillRequest) => __TAURI_INVOKE<SkillDetailPayload>("save_skill", { payload }),
	deleteSkill: (payload: DeleteSkillRequest) => __TAURI_INVOKE<DeleteSkillPayload>("delete_skill", { payload }),
	applyWindowStage: (stage: WindowStage) => __TAURI_INVOKE<null>("apply_window_stage", { stage }),
	setWindowBackground: (input: SetWindowBackgroundInput, traceId: string | null) => __TAURI_INVOKE<null>("set_window_background", { input, traceId }),
	createWorkspacePath: (payload: WorkspacePathCreateRequest) => __TAURI_INVOKE<WorkspacePathCreatePayload>("create_workspace_path", { payload }),
	deleteWorkspacePath: (payload: WorkspacePathDeleteRequest) => __TAURI_INVOKE<WorkspacePathDeletePayload>("delete_workspace_path", { payload }),
	listWorkspaceEntries: (path: string | null, rootPath: string | null) => __TAURI_INVOKE<WorkspaceDirectoryPayload>("list_workspace_entries", { path, rootPath }),
	loadImageAsset: (path: string) => __TAURI_INVOKE<ImageAssetPayload>("load_image_asset", { path }),
	loadScript: (path: string, workspaceRootPath: string | null) => __TAURI_INVOKE<ScriptFilePayload>("load_script", { path, workspaceRootPath }),
	renameWorkspacePath: (payload: WorkspacePathRenameRequest) => __TAURI_INVOKE<WorkspacePathRenamePayload>("rename_workspace_path", { payload }),
	saveScript: (payload: SaveScriptRequest) => __TAURI_INVOKE<ScriptFilePayload>("save_script", { payload }),
	/**
	 *  启动（或重启）工作区文件监听
	 * 
	 *  真正的目录遍历与监听在后台线程完成，本命令仅做根目录校验与 watcher 构造后
	 *  立即返回，因此打开超大仓库也不会阻塞前端。监听结果通过 `WorkspaceFsEvent` 推送。
	 *  若已有监听，会先换入新句柄再通知旧线程退出，旧 watcher 在其线程结束时 Drop。
	 * 
	 *  # 参数
	 *  - `root_path`: 工作区根目录的绝对或相对路径，会被 canonicalize
	 * 
	 *  # 错误
	 *  路径不存在 / 不是目录、或 watcher 构造失败时返回 `Err(String)`。
	 *  注意：后台的实际 watch 调用失败只记日志，不再同步抛出（后台化的取舍）。
	 */
	startWorkspaceWatching: (rootPath: string) => __TAURI_INVOKE<null>("start_workspace_watching", { rootPath }),
	/**
	 *  停止工作区文件监听
	 * 
	 *  通知后台线程退出；线程在 `DEBOUNCE_DURATION` 内跳出循环并 Drop watcher。
	 *  重复调用、未启动时调用都是安全的（幂等）。
	 */
	stopWorkspaceWatching: () => __TAURI_INVOKE<null>("stop_workspace_watching"),
	ensureTerminalSession: (payload: EnsureTerminalSessionRequest) => __TAURI_INVOKE<TerminalSessionPayload>("ensure_terminal_session", { payload }),
	writeTerminalInput: (payload: TerminalInputRequest) => __TAURI_INVOKE<null>("write_terminal_input", { payload }),
	resizeTerminalSession: (payload: TerminalResizeRequest) => __TAURI_INVOKE<null>("resize_terminal_session", { payload }),
	closeTerminalSession: (payload: CloseTerminalSessionRequest) => __TAURI_INVOKE<null>("close_terminal_session", { payload }),
	dispatchScriptToTerminal: (payload: DispatchTerminalScriptRequest) => __TAURI_INVOKE<DispatchTerminalScriptPayload>("dispatch_script_to_terminal", { payload }),
	cancelTerminalRun: (payload: CancelTerminalRunRequest) => __TAURI_INVOKE<null>("cancel_terminal_run", { payload }),
	listGitBranches: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitBranchListPayload>("list_git_branches", { payload }),
	checkoutGitBranch: (payload: GitBranchCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_branch", { payload }),
	/**
	 *  以分离 HEAD 方式检出指定提交（等价 `git checkout <commit>`）。
	 *  复用分支切换的工作区 / 索引 / HEAD 同步实现；要求工作区干净。
	 */
	checkoutGitCommit: (payload: GitCommitCheckoutRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("checkout_git_commit", { payload }),
	createGitBranch: (payload: GitBranchCreateRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("create_git_branch", { payload }),
	getGitDiffPreview: (payload: GitDiffPreviewRequest) => __TAURI_INVOKE<GitDiffPreviewPayload>("get_git_diff_preview", { payload }),
	/**  返回特定提交中单个文件的 diff（对比父提交）。 */
	getGitCommitFileDiff: (payload: GitCommitFileDiffRequest) => __TAURI_INVOKE<GitCommitFileDiffPayload>("get_git_commit_file_diff", { payload }),
	/**
	 *  返回特定提交中单个文件的主界面 Diff 预览（对比父提交）。
	 *  复用与工作区/暂存区 Diff 相同的只读 Diff 视图（GitDiffViewer / openGitDiffDocument）。
	 */
	getGitCommitFileDiffPreview: (payload: GitCommitFileDiffRequest) => __TAURI_INVOKE<GitDiffPreviewPayload>("get_git_commit_file_diff_preview", { payload }),
	getGithubAuthStatus: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("get_github_auth_status", { payload }),
	beginGithubBrowserAuth: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubBrowserAuthPayload>("begin_github_browser_auth", { payload }),
	completeGithubBrowserAuth: (payload: GitHubBrowserAuthCompleteRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("complete_github_browser_auth", { payload }),
	connectGithub: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("connect_github", { payload }),
	disconnectGithub: (payload: GitHubAuthRequest) => __TAURI_INVOKE<GitHubAuthStatusPayload>("disconnect_github", { payload }),
	listGitCommitHistory: (payload: GitCommitHistoryRequest) => __TAURI_INVOKE<GitCommitHistoryPayload>("list_git_commit_history", { payload }),
	/**
	 *  读取单个提交的详细信息（用于历史悬浮卡片）：提交元数据 + 相对首个父提交的
	 *  文件/行变更聚合（文件数、插入、删除）。根提交对空树取差异。
	 */
	getGitCommitDetail: (payload: GitCommitDetailRequest) => __TAURI_INVOKE<GitCommitDetailPayload>("get_git_commit_detail", { payload }),
	getGitPullRequestSupport: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("get_git_pull_request_support", { payload }),
	setGitRemote: (payload: GitRemoteSetRequest) => __TAURI_INVOKE<GitPullRequestSupportPayload>("set_git_remote", { payload }),
	listGitPullRequests: (payload: GitPullRequestListRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload[]>("list_git_pull_requests", { payload }),
	getGitPullRequestDetail: (payload: GitPullRequestDetailRequest) => __TAURI_INVOKE<GitPullRequestDetailPayload>("get_git_pull_request_detail", { payload }),
	createGitPullRequest: (payload: GitPullRequestCreateRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("create_git_pull_request", { payload }),
	mergeGitPullRequest: (payload: GitPullRequestMergeRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("merge_git_pull_request", { payload }),
	closeGitPullRequest: (payload: GitPullRequestCloseRequest) => __TAURI_INVOKE<GitPullRequestSummaryPayload>("close_git_pull_request", { payload }),
	/**
	 *  回滚指定提交：把该提交的改动反向应用到工作区与索引（等价 `git revert --no-commit`）。
	 *  要求工作区干净；结果以「已暂存」状态呈现，用户检查后可直接提交。
	 */
	revertGitCommit: (payload: GitCommitRevertRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("revert_git_commit", { payload }),
	listGitStashes: (payload: GitRepositoryRootRequest) => __TAURI_INVOKE<GitStashListPayload>("list_git_stashes", { payload }),
	saveGitStash: (payload: GitStashSaveRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("save_git_stash", { payload }),
	applyGitStash: (payload: GitStashApplyRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("apply_git_stash", { payload }),
	dropGitStash: (payload: GitStashDropRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("drop_git_stash", { payload }),
	getGitRepositoryStatus: (workspaceRootPath: string | null) => __TAURI_INVOKE<GitRepositoryStatusPayload>("get_git_repository_status", { workspaceRootPath }),
	initGitRepository: (workspaceRootPath: string | null) => __TAURI_INVOKE<GitRepositoryStatusPayload>("init_git_repository", { workspaceRootPath }),
	getGitFileBaseline: (path: string) => __TAURI_INVOKE<GitFileBaselinePayload>("get_git_file_baseline", { path }),
	stageGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("stage_git_paths", { payload }),
	unstageGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("unstage_git_paths", { payload }),
	commitGitIndex: (payload: GitCommitRequest) => __TAURI_INVOKE<GitCommitResultPayload>("commit_git_index", { payload }),
	discardGitPaths: (payload: GitPathOperationRequest) => __TAURI_INVOKE<GitRepositoryStatusPayload>("discard_git_paths", { payload }),
	testSshConnection: (payload: SshConnectionTestRequest) => __TAURI_INVOKE<SshConnectionTestPayload>("test_ssh_connection", { payload }),
	trustSshHostKey: (host: string, port: number) => __TAURI_INVOKE<SshHostKeyTrustPayload>("trust_ssh_host_key", { host, port }),
	saveSshPassword: (payload: SshPasswordSaveRequest) => __TAURI_INVOKE<SshPasswordStatusPayload>("save_ssh_password", { payload }),
	getSshPassword: (payload: SshPasswordGetRequest) => __TAURI_INVOKE<SshPasswordPayload>("get_ssh_password", { payload }),
	listSshConfigHosts: () => __TAURI_INVOKE<SshConfigHostPayload[]>("list_ssh_config_hosts"),
	listSshDirectory: (payload: SshDirectoryListRequest) => __TAURI_INVOKE<SshDirectoryListPayload>("list_ssh_directory", { payload }),
	downloadSshFile: (payload: SshFileDownloadRequest) => __TAURI_INVOKE<SshFileDownloadPayload>("download_ssh_file", { payload }),
	uploadSshFile: (payload: SshFileUploadRequest) => __TAURI_INVOKE<SshFileUploadPayload>("upload_ssh_file", { payload }),
	readSshFile: (payload: SshFileReadRequest) => __TAURI_INVOKE<SshFileReadPayload>("read_ssh_file", { payload }),
	writeSshFile: (payload: SshFileWriteRequest) => __TAURI_INVOKE<SshFileWritePayload>("write_ssh_file", { payload }),
	deleteSshPath: (payload: SshPathDeleteRequest) => __TAURI_INVOKE<SshPathDeletePayload>("delete_ssh_path", { payload }),
	renameSshPath: (payload: SshPathRenameRequest) => __TAURI_INVOKE<SshPathRenamePayload>("rename_ssh_path", { payload }),
	createSshDirectory: (payload: SshDirectoryCreateRequest) => __TAURI_INVOKE<SshDirectoryCreatePayload>("create_ssh_directory", { payload }),
	agentSidecarHealth: () => __TAURI_INVOKE<AgentSidecarHealthPayload>("agent_sidecar_health"),
	agentSidecarRestart: () => __TAURI_INVOKE<AgentSidecarHealthPayload>("agent_sidecar_restart"),
	agentSidecarWarmup: () => __TAURI_INVOKE<AgentSidecarWarmupPayload>("agent_sidecar_warmup"),
	agentSidecarChat: (payload: AgentSidecarChatRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_chat", { payload }),
	/**
	 *  外部 ACP 编码 agent（Kimi Code / Codex 等，ADR-0015）的标准回合命令（`session/prompt`）。
	 * 
	 *  与 `agent_sidecar_chat`（走自家边车的带外 `agent_chat` 扩展回合）不同：按后端类型经
	 *  `get_or_spawn_backend` 解析/派生对应的独立常驻宿主，解析稳定会话后以纯文本内容块驱动
	 *  一轮标准 prompt。**不补齐 model_config**——外部 agent 的凭据由其自身 CLI 自管（见
	 *  acp/launch.rs；如 Kimi 需先在终端 `kimi` 内 `/login`）。过程增量经 session/update 帧转发
	 *  （投影见 acp/ui_event.rs），本命令仅返回终态：会话标识 + 回合终止原因。
	 */
	agentSidecarExternalChat: (payload: AgentExternalChatRequest_Deserialize) => __TAURI_INVOKE<AgentExternalChatResultPayload>("agent_sidecar_external_chat", { payload }),
	agentSidecarResolveApproval: (payload: AgentSidecarApprovalResolveRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_resolve_approval", { payload }),
	agentSidecarResolveAskUser: (payload: AgentSidecarAskUserResumeRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_resolve_ask_user", { payload }),
	agentSidecarRestoreCheckpoint: (payload: AgentSidecarCheckpointRestoreRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarResponsePayload>("agent_sidecar_restore_checkpoint", { payload }),
	agentSidecarOrchestrate: (payload: AgentSidecarOrchestrateRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarOrchestratePayload>("agent_sidecar_orchestrate", { payload }),
	agentSidecarOrchestrateResume: (payload: AgentSidecarOrchestrateResumeRequest_Deserialize) => __TAURI_INVOKE<AgentSidecarOrchestratePayload>("agent_sidecar_orchestrate_resume", { payload }),
	/**  Create (or reuse) the child webview and start the CDP control plane. Idempotent. */
	agentWebviewCreate: (input: AgentWebviewCreateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_create", { input, traceId }),
	/**  Sync child webview bounds. */
	agentWebviewSetBounds: (input: AgentWebviewBoundsInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_set_bounds", { input, traceId }),
	/**  Show/hide the child webview. */
	agentWebviewSetVisible: (input: AgentWebviewVisibleInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_set_visible", { input, traceId }),
	/**  Navigate to a new URL (address bar). */
	agentWebviewNavigate: (input: AgentWebviewNavigateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_navigate", { input, traceId }),
	/**  Back one entry (CDP real history). */
	agentWebviewBack: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_back", { traceId }),
	/**  Forward one entry (CDP real history). */
	agentWebviewForward: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_forward", { traceId }),
	/**  Reload current page (CDP Page.reload). */
	agentWebviewReload: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_reload", { traceId }),
	/**
	 *  Enter element-pick mode by injecting the @medv/finder picker. The next element the user
	 *  clicks is captured and surfaced via AgentWebviewElementPickedEvent.
	 */
	agentWebviewStartSelect: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_start_select", { traceId }),
	/**  Exit element-pick mode without picking (tears down the injected picker). */
	agentWebviewCancelSelect: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_cancel_select", { traceId }),
	/**  Open the given URL in the system default browser (official tauri-plugin-opener, Rust-side). */
	agentWebviewOpenExternal: (input: AgentWebviewNavigateInput, traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_open_external", { input, traceId }),
	/**  Destroy the child webview and tear down the CDP session. Idempotent. */
	agentWebviewDestroy: (traceId: string | null) => __TAURI_INVOKE<null>("agent_webview_destroy", { traceId }),
	aiGetConfig: () => __TAURI_INVOKE<AiConfigPayload>("ai_get_config"),
	aiSaveConfig: (payload: AiSaveConfigRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_config", { payload }),
	aiSaveCredentials: (payload: AiSaveCredentialsRequest) => __TAURI_INVOKE<AiConfigPayload>("ai_save_credentials", { payload }),
	aiTestProviderConfig: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider_config", { payload }),
	aiConnectProvider: (payload: AiProviderConnectionRequest) => __TAURI_INVOKE<AiProviderConnectionPayload>("ai_connect_provider", { payload }),
	aiClearCredentials: () => __TAURI_INVOKE<null>("ai_clear_credentials"),
	aiTestProvider: () => __TAURI_INVOKE<AiProviderTestPayload>("ai_test_provider"),
	aiGenerateConversationTitle: (payload: AiConversationTitleRequest) => __TAURI_INVOKE<AiConversationTitlePayload>("ai_generate_conversation_title", { payload }),
	aiGetSuggestionPoolCache: () => __TAURI_INVOKE<{
	suggestions: string[],
	model: string,
	generatedAt: string,
} | null>("ai_get_suggestion_pool_cache"),
	aiGenerateSuggestionPool: (payload: AiSuggestionPoolRequest) => __TAURI_INVOKE<AiSuggestionPoolPayload>("ai_generate_suggestion_pool", { payload }),
	aiChatStream: (payload: AiChatRequest) => __TAURI_INVOKE<AiChatStreamPayload>("ai_chat_stream", { payload }),
	aiCancel: (payload: AiCancelRequest) => __TAURI_INVOKE<null>("ai_cancel", { payload }),
	/**
	 *  投递 ACP 反向权限请求（`session/request_permission`）的审批决策，唤醒回合内挂起的工具调用。
	 * 
	 *  与 `ai_cancel` 同构地委托给 Tauri 托管的 `AcpRuntime`：会话归属哪个后端宿主对命令层透明，
	 *  由 runtime 向全部已建立宿主广播投递。三字段先行空白校验（前端总能从已渲染审批气泡取得）；
	 *  返回是否命中某挂起审批——`false` 表示无匹配（多为已超时/被取消/重复投递的良性竞态，
	 *  命令层不视作错误，交前端自行决定是否提示），与 runtime 的「安全空操作」语义一致。
	 */
	aiResolveApproval: (payload: AiResolveApprovalRequest) => __TAURI_INVOKE<boolean>("ai_resolve_approval", { payload }),
	aiInlineComplete: (payload: AiInlineCompletionRequest) => __TAURI_INVOKE<AiInlineCompletionResult>("ai_inline_complete", { payload }),
	aiAgentClassifyTask: (payload: AiAgentClassifyTaskRequest) => __TAURI_INVOKE<AiAgentClassifyTaskPayload>("ai_agent_classify_task", { payload }),
	aiAgentSetNetworkPermission: (payload: AiAgentSetNetworkPermissionRequest) => __TAURI_INVOKE<AiAgentNetworkPermissionPayload>("ai_agent_set_network_permission", { payload }),
	aiWebSearch: (payload: AiWebSearchInput) => __TAURI_INVOKE<AiWebSearchPayload>("ai_web_search", { payload }),
	aiWebFetch: (payload: AiWebFetchInput) => __TAURI_INVOKE<AiWebFetchPayload>("ai_web_fetch", { payload }),
	aiProposePatch: (payload: AiProposePatchRequest) => __TAURI_INVOKE<AiProposePatchPayload>("ai_propose_patch", { payload }),
	aiApplyPatch: (payload: AiApplyPatchRequest) => __TAURI_INVOKE<AiApplyPatchPayload>("ai_apply_patch", { payload }),
	aiEditGetAuthLevel: () => __TAURI_INVOKE<AiEditAuthStatePayload>("ai_edit_get_auth_level"),
	aiEditSetAuthLevel: (payload: AiEditSetAuthLevelRequest) => __TAURI_INVOKE<AiEditAuthStatePayload>("ai_edit_set_auth_level", { payload }),
	aiEditListTimeline: (payload: AiEditListTimelineRequest) => __TAURI_INVOKE<AiEditListTimelinePayload>("ai_edit_list_timeline", { payload }),
	aiEditSetPin: (payload: AiEditSetPinRequest) => __TAURI_INVOKE<AiEditSetPinPayload>("ai_edit_set_pin", { payload }),
	aiEditGetDiff: (payload: AiEditGetDiffRequest) => __TAURI_INVOKE<AiEditGetDiffPayload>("ai_edit_get_diff", { payload }),
	aiEditCreateSnapshot: (payload: AiEditCreateSnapshotRequest) => __TAURI_INVOKE<AiEditCreateSnapshotPayload>("ai_edit_create_snapshot", { payload }),
	aiEditRestoreSnapshot: (payload: AiEditRestoreSnapshotRequest) => __TAURI_INVOKE<AiEditRestoreSnapshotPayload>("ai_edit_restore_snapshot", { payload }),
	aiEditUndoOperation: (payload: AiEditUndoOperationRequest) => __TAURI_INVOKE<AiEditUndoOperationPayload>("ai_edit_undo_operation", { payload }),
	aiEditRevertFile: (payload: AiEditRevertFileRequest) => __TAURI_INVOKE<AiEditRevertFilePayload>("ai_edit_revert_file", { payload }),
	aiEditRevertHunk: (payload: AiEditRevertHunkRequest) => __TAURI_INVOKE<AiEditRevertHunkPayload>("ai_edit_revert_hunk", { payload }),
	aiEditRevertTask: (payload: AiEditRevertTaskRequest) => __TAURI_INVOKE<AiEditRevertTaskPayload>("ai_edit_revert_task", { payload }),
	lspStart: (workspaceRoot: string) => __TAURI_INVOKE<null>("lsp_start", { workspaceRoot }),
	lspStop: () => __TAURI_INVOKE<null>("lsp_stop"),
	lspDidOpen: (filePath: string, content: string, languageId: string) => __TAURI_INVOKE<null>("lsp_did_open", { filePath, content, languageId }),
	lspDidChange: (filePath: string, content: string, version: number, changes: LspContentChange_Deserialize[] | null) => __TAURI_INVOKE<null>("lsp_did_change", { filePath, content, version, changes }),
	lspDidClose: (filePath: string) => __TAURI_INVOKE<null>("lsp_did_close", { filePath }),
	lspCompletion: (filePath: string, line: number, column: number) => __TAURI_INVOKE<LspCompletionItem[]>("lsp_completion", { filePath, line, column }),
	lspHover: (filePath: string, line: number, column: number) => __TAURI_INVOKE<{
	contents: string,
} | null>("lsp_hover", { filePath, line, column }),
};

/** Events */
export const events = {
	agentWebviewConsoleEvent: makeEvent<AgentWebviewConsoleEvent>("agent-webview-console-event"),
	agentWebviewElementPickedEvent: makeEvent<AgentWebviewElementPickedEvent>("agent-webview-element-picked-event"),
	agentWebviewNavigatedEvent: makeEvent<AgentWebviewNavigatedEvent>("agent-webview-navigated-event"),
	workspaceFsEvent: makeEvent<WorkspaceFsEvent>("workspace-fs-event"),
	workspaceSearchStreamEvent: makeEvent<WorkspaceSearchStreamEvent>("workspace-search-stream-event"),
};

/* Types */
/**
 *  可挂载的外部 ACP 编码 agent 后端类型（ADR-0015）。
 * 
 *  作为 specta 契约类型导出给前端选择，运行时由命令层映射到 `acp::AcpBackendId`：
 *    * `Builtin` —— 自家 Node Mastra 边车（默认后端，走带外 `agent_chat` 扩展回合）；
 *    * `Kimi`    —— Kimi Code（`kimi acp`，原生 ACP，凭终端 `/login` 自鉴权）；
 *    * `Codex`   —— Codex CLI（社区 `codex-acp` 适配器，凭 `OPENAI_API_KEY`）。
 */
export type AgentBackendKind = "builtin" | "kimi" | "codex";

/**
 *  外部 ACP 编码 agent 的标准回合（`session/prompt`）请求（契约层）。
 * 
 *  与自家 `AgentSidecarChatRequest` 不同：外部 agent 只实现标准 `prompt`、不认识
 *  `calamex.dev/*` 扩展方法，也不接收逐请求 `model_config`（凭据由其自身 CLI 自管，见
 *  ADR-0015 / `acp/launch.rs`），故仅携带后端类型、纯文本提示与会话定位字段。
 */
export type AgentExternalChatRequest = AgentExternalChatRequest_Serialize | AgentExternalChatRequest_Deserialize;

/**
 *  外部 ACP 编码 agent 的标准回合（`session/prompt`）请求（契约层）。
 * 
 *  与自家 `AgentSidecarChatRequest` 不同：外部 agent 只实现标准 `prompt`、不认识
 *  `calamex.dev/*` 扩展方法，也不接收逐请求 `model_config`（凭据由其自身 CLI 自管，见
 *  ADR-0015 / `acp/launch.rs`），故仅携带后端类型、纯文本提示与会话定位字段。
 */
export type AgentExternalChatRequest_Deserialize = {
	backend: AgentBackendKind,
	text: string,
	threadId: string | null,
	workspaceRootPath: string | null,
};

/**
 *  外部 ACP 编码 agent 的标准回合（`session/prompt`）请求（契约层）。
 * 
 *  与自家 `AgentSidecarChatRequest` 不同：外部 agent 只实现标准 `prompt`、不认识
 *  `calamex.dev/*` 扩展方法，也不接收逐请求 `model_config`（凭据由其自身 CLI 自管，见
 *  ADR-0015 / `acp/launch.rs`），故仅携带后端类型、纯文本提示与会话定位字段。
 */
export type AgentExternalChatRequest_Serialize = {
	backend: AgentBackendKind,
	text: string,
	threadId?: string | null,
	workspaceRootPath?: string | null,
};

/**
 *  外部 ACP 回合的终态结果（契约层）。
 * 
 *  外部 agent 无自家富信封：过程增量经 `session/update` 帧由 `EventSink` 转发（投影见
 *  `acp/ui_event.rs`），本结果仅承载会话标识与回合终止原因（`StopReason` 的字符串化）。
 */
export type AgentExternalChatResultPayload = {
	sessionId: string,
	stopReason: string,
};

export type AgentSidecarApprovalResolveRequest = AgentSidecarApprovalResolveRequest_Serialize | AgentSidecarApprovalResolveRequest_Deserialize;

export type AgentSidecarApprovalResolveRequest_Deserialize = {
	sessionId: string | null,
	requestId: string,
	decision: string,
	goal: string | null,
	messages?: AgentSidecarMessagePayload[],
	workspaceRootPath: string | null,
	context?: AiContextReferencePayload[],
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
	threadId: string | null,
	planId: string | null,
	planVersion: number | null,
	planStepId: string | null,
};

export type AgentSidecarApprovalResolveRequest_Serialize = {
	sessionId?: string | null,
	requestId: string,
	decision: string,
	goal?: string | null,
	messages: AgentSidecarMessagePayload[],
	workspaceRootPath?: string | null,
	context: AiContextReferencePayload[],
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
	threadId?: string | null,
	planId?: string | null,
	planVersion?: number | null,
	planStepId?: string | null,
};

/**
 *  `calamex.dev/agent/ask-user/resume` 单题作答（契约层）。
 *  镜像 sidecar `askUserAnswerParamsSchema`：questionId、optionIds（缺省 []）、text（可选）。
 *  optionIds 恒序列化为数组（空则 []）；text 空白修剪由接线层负责，契约层仅在 None 时省略键。
 */
export type AgentSidecarAskUserAnswerPayload = AgentSidecarAskUserAnswerPayload_Serialize | AgentSidecarAskUserAnswerPayload_Deserialize;

/**
 *  `calamex.dev/agent/ask-user/resume` 单题作答（契约层）。
 *  镜像 sidecar `askUserAnswerParamsSchema`：questionId、optionIds（缺省 []）、text（可选）。
 *  optionIds 恒序列化为数组（空则 []）；text 空白修剪由接线层负责，契约层仅在 None 时省略键。
 */
export type AgentSidecarAskUserAnswerPayload_Deserialize = {
	questionId: string,
	optionIds?: string[],
	text: string | null,
};

/**
 *  `calamex.dev/agent/ask-user/resume` 单题作答（契约层）。
 *  镜像 sidecar `askUserAnswerParamsSchema`：questionId、optionIds（缺省 []）、text（可选）。
 *  optionIds 恒序列化为数组（空则 []）；text 空白修剪由接线层负责，契约层仅在 None 时省略键。
 */
export type AgentSidecarAskUserAnswerPayload_Serialize = {
	questionId: string,
	optionIds: string[],
	text?: string | null,
};

/**
 *  `calamex.dev/agent/ask-user/resume` 恢复请求（契约层）。
 * 
 *  结构镜像 `AgentSidecarApprovalResolveRequest` 的「agentChat 基底 + requestId」，但以
 *  `outcome` + 结构化 `answers` 取代 `decision`：
 *    * outcome 取值（selected/cancelled）由 sidecar zod 校验，原样透传；
 *    * answers 为每题作答，outcome=cancelled 时通常缺省（serde 整字段省略，对齐 zod `.optional()`）。
 * 
 *  与 approval 恢复一致地携带 plan_*（plan 续跑定位），不含 `mode`（恢复不切换模式）。
 */
export type AgentSidecarAskUserResumeRequest = AgentSidecarAskUserResumeRequest_Serialize | AgentSidecarAskUserResumeRequest_Deserialize;

/**
 *  `calamex.dev/agent/ask-user/resume` 恢复请求（契约层）。
 * 
 *  结构镜像 `AgentSidecarApprovalResolveRequest` 的「agentChat 基底 + requestId」，但以
 *  `outcome` + 结构化 `answers` 取代 `decision`：
 *    * outcome 取值（selected/cancelled）由 sidecar zod 校验，原样透传；
 *    * answers 为每题作答，outcome=cancelled 时通常缺省（serde 整字段省略，对齐 zod `.optional()`）。
 * 
 *  与 approval 恢复一致地携带 plan_*（plan 续跑定位），不含 `mode`（恢复不切换模式）。
 */
export type AgentSidecarAskUserResumeRequest_Deserialize = {
	sessionId: string | null,
	requestId: string,
	outcome: string,
	answers: AgentSidecarAskUserAnswerPayload_Deserialize[] | null,
	goal: string | null,
	messages?: AgentSidecarMessagePayload[],
	workspaceRootPath: string | null,
	context?: AiContextReferencePayload[],
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
	threadId: string | null,
	planId: string | null,
	planVersion: number | null,
	planStepId: string | null,
};

/**
 *  `calamex.dev/agent/ask-user/resume` 恢复请求（契约层）。
 * 
 *  结构镜像 `AgentSidecarApprovalResolveRequest` 的「agentChat 基底 + requestId」，但以
 *  `outcome` + 结构化 `answers` 取代 `decision`：
 *    * outcome 取值（selected/cancelled）由 sidecar zod 校验，原样透传；
 *    * answers 为每题作答，outcome=cancelled 时通常缺省（serde 整字段省略，对齐 zod `.optional()`）。
 * 
 *  与 approval 恢复一致地携带 plan_*（plan 续跑定位），不含 `mode`（恢复不切换模式）。
 */
export type AgentSidecarAskUserResumeRequest_Serialize = {
	sessionId?: string | null,
	requestId: string,
	outcome: string,
	answers?: AgentSidecarAskUserAnswerPayload_Serialize[] | null,
	goal?: string | null,
	messages: AgentSidecarMessagePayload[],
	workspaceRootPath?: string | null,
	context: AiContextReferencePayload[],
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
	threadId?: string | null,
	planId?: string | null,
	planVersion?: number | null,
	planStepId?: string | null,
};

export type AgentSidecarChatRequest = AgentSidecarChatRequest_Serialize | AgentSidecarChatRequest_Deserialize;

export type AgentSidecarChatRequest_Deserialize = {
	sessionId: string | null,
	mode: string | null,
	goal: string | null,
	messages: AgentSidecarMessagePayload[],
	workspaceRootPath: string | null,
	context?: AiContextReferencePayload[],
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
	threadId: string | null,
};

export type AgentSidecarChatRequest_Serialize = {
	sessionId?: string | null,
	mode?: string | null,
	goal?: string | null,
	messages: AgentSidecarMessagePayload[],
	workspaceRootPath?: string | null,
	context: AiContextReferencePayload[],
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
	threadId?: string | null,
};

export type AgentSidecarCheckpointRestoreRequest = AgentSidecarCheckpointRestoreRequest_Serialize | AgentSidecarCheckpointRestoreRequest_Deserialize;

export type AgentSidecarCheckpointRestoreRequest_Deserialize = {
	sessionId: string | null,
	runId: string,
	snapshotId: string | null,
	step: AgentSidecarRollbackStepPath | null,
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
};

export type AgentSidecarCheckpointRestoreRequest_Serialize = {
	sessionId?: string | null,
	runId: string,
	snapshotId?: string | null,
	step?: AgentSidecarRollbackStepPath | null,
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
};

export type AgentSidecarHealthPayload = {
	ok: boolean,
	status: string,
	engine: string,
	version: string | null,
	protocolVersion: string | null,
	implementationVersion: string | null,
	mcp: AgentSidecarMcpHealthPayload,
};

export type AgentSidecarMcpHealthPayload = {
	configuredServers: number,
	serverNames: string[],
	errors: string[],
};

export type AgentSidecarMessagePayload = {
	role: string,
	content: string,
};

export type AgentSidecarModelConfigPayload = AgentSidecarModelConfigPayload_Serialize | AgentSidecarModelConfigPayload_Deserialize;

export type AgentSidecarModelConfigPayload_Deserialize = {
	modelId: string,
	apiKey: SecretString,
	baseUrl: string | null,
};

export type AgentSidecarModelConfigPayload_Serialize = {
	modelId: string,
	apiKey: SecretString,
	baseUrl?: string | null,
};

export type AgentSidecarOrchestratePayload = {
	runId: string,
	/**
	 *  Final orchestration result; passed through verbatim and validated by the
	 *  frontend (Zod). Mapped to TS `unknown` via specta_typescript::Unknown to
	 *  avoid serde_json::Number tripping specta's BigInt-forbidden check.
	 */
	result?: unknown,
};

export type AgentSidecarOrchestrateRequest = AgentSidecarOrchestrateRequest_Serialize | AgentSidecarOrchestrateRequest_Deserialize;

export type AgentSidecarOrchestrateRequest_Deserialize = {
	sessionId: string | null,
	goal: string,
	threadId: string | null,
	/**
	 *  Per-run execution preference (`interactive` | `autonomous`), threaded
	 *  through verbatim like `thread_id` and validated by the sidecar (Zod
	 *  enum, defaults to `interactive`). Omitted from the body when blank so the
	 *  sidecar applies its default; the Rust layer never interprets the value.
	 */
	executionMode: string | null,
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
};

export type AgentSidecarOrchestrateRequest_Serialize = {
	sessionId?: string | null,
	goal: string,
	threadId?: string | null,
	/**
	 *  Per-run execution preference (`interactive` | `autonomous`), threaded
	 *  through verbatim like `thread_id` and validated by the sidecar (Zod
	 *  enum, defaults to `interactive`). Omitted from the body when blank so the
	 *  sidecar applies its default; the Rust layer never interprets the value.
	 */
	executionMode?: string | null,
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
};

export type AgentSidecarOrchestrateResumeRequest = AgentSidecarOrchestrateResumeRequest_Serialize | AgentSidecarOrchestrateResumeRequest_Deserialize;

export type AgentSidecarOrchestrateResumeRequest_Deserialize = {
	runId: string,
	decision: string,
	reason: string | null,
	modelConfig: AgentSidecarModelConfigPayload_Deserialize | null,
};

export type AgentSidecarOrchestrateResumeRequest_Serialize = {
	runId: string,
	decision: string,
	reason?: string | null,
	modelConfig?: AgentSidecarModelConfigPayload_Serialize | null,
};

export type AgentSidecarResponsePayload = {
	sessionId: string,
	/**
	 *  逐事件透传的任意 JSON，由前端自行 Zod 校验；
	 *  用 specta_typescript::Unknown 将导出类型映射为 TS `unknown[]`，
	 *  避开 serde_json::Number 的 i64/u64 触发 specta BigInt-forbidden；
	 *  serde 运行时仍为 Vec<serde_json::Value>，行为不变。
	 */
	events: unknown[],
	result: string | null,
};

export type AgentSidecarRollbackStepPath = string | string[];

export type AgentSidecarWarmupPayload = {
	ok: boolean,
	providerId: string | null,
	origin: string | null,
	statusCode: number | null,
	durationMs: number,
	skipped: boolean,
	reason: string | null,
};

export type AgentWebviewBoundsInput = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  One console line (console.* call or browser-level log entry). */
export type AgentWebviewConsoleEvent = {
	/**  "log" | "warn" | "error" */
	level: string,
	message: string,
	/**  epoch milliseconds */
	timestamp: number | null,
};

export type AgentWebviewCreateInput = {
	url: string,
	remoteDebuggingPort: number,
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  User picked an element via the select tool -> element context for the AI. */
export type AgentWebviewElementPickedEvent = {
	/**  Page URL the element was picked from. */
	url: string,
	/**  Robust CSS selector for the element (via @medv/finder). */
	label: string,
	/**  Truncated outerHTML for AI context. */
	outerHtml: string,
};

export type AgentWebviewNavigateInput = {
	url: string,
};

/**  Main-frame navigation completed -> push latest url + back/forward availability. */
export type AgentWebviewNavigatedEvent = {
	url: string,
	canGoBack: boolean,
	canGoForward: boolean,
};

export type AgentWebviewVisibleInput = {
	visible: boolean,
};

export type AiAgentClassifyTaskPayload = {
	classification: string,
	shouldEnterPlanMode: boolean,
	reason: string,
};

export type AiAgentClassifyTaskRequest = {
	goal: string,
	context: AiContextReferencePayload[],
};

export type AiAgentNetworkPermissionPayload = {
	permission: string,
};

export type AiAgentSetNetworkPermissionRequest = {
	permission: string,
};

export type AiApplyPatchFilePayload = {
	path: string,
	byteSize: number,
};

export type AiApplyPatchMetadataRequest = {
	taskId: string | null,
	turnId: string | null,
	reason: string | null,
	toolCallId: string | null,
	confirmedByUser: boolean | null,
	agentRunId: string | null,
	agentStepId: string | null,
	workspaceRootPath: string | null,
};

export type AiApplyPatchPayload = {
	appliedFiles: AiApplyPatchFilePayload[],
};

export type AiApplyPatchRequest = {
	patch: AiPatchSetPayload,
	metadata: AiApplyPatchMetadataRequest | null,
};

export type AiCancelRequest = {
	streamId: string,
	threadId: string | null,
};

export type AiChatMessagePayload = {
	/**  已知值："user" | "assistant" | "system" | "tool"。 */
	role: string,
	content: string,
	id: string,
	createdAt: string,
	references: AiContextReferencePayload[],
};

export type AiChatRequest = {
	threadId: string | null,
	messages: AiChatMessagePayload[],
	references: AiContextReferencePayload[],
};

export type AiChatStreamPayload = {
	streamId: string,
	assistantMessageId: string,
	providerType: string,
	model: string,
	sessionId: string,
};

export type AiConfigPayload = {
	providerType: string,
	selectedModel: string | null,
	baseUrl: string | null,
	isBaseUrlConfigured: boolean,
	hasCredentials: boolean,
	isConfigured: boolean,
	inlineCompletionEnabled: boolean,
	chatEnabled: boolean,
	agentEnabled: boolean,
	narrator: AiModelEndpointConfigPayload,
	credentials: AiCredentialStatusPayload[],
};

export type AiContextRangePayload = {
	startLine: number,
	endLine: number,
};

export type AiContextReferencePayload = {
	id: string,
	/**  引用种类，已知值："file" | "selection" | "symbol" | "diagnostic" | …。 */
	kind: string,
	label: string,
	path: string | null,
	range: AiContextRangePayload | null,
	contentPreview: string,
	redacted: boolean,
};

export type AiConversationTitlePayload = {
	title: string,
	model: string,
};

export type AiConversationTitleRequest = {
	userMessage: string,
	assistantMessage: string,
};

export type AiCredentialStatusPayload = {
	providerId: string,
	hasCredentials: boolean,
	alias: string,
	keyPreview: string,
};

export type AiEditAuthStatePayload = {
	/**  已知值："manual" | "per_task" | "session"。 */
	level: string,
	taskId: string | null,
	updatedAt: string,
};

export type AiEditCreateSnapshotPayload = {
	snapshot: AiSnapshotPayload,
};

export type AiEditCreateSnapshotRequest = {
	fileRefs: string[],
	label: string | null,
	taskId: string | null,
};

export type AiEditDiffHunkPayload = {
	hunkIndex: number,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	lines: string[],
};

export type AiEditGetDiffPayload = {
	taskId: string,
	path: string,
	operationId: string,
	kind: string,
	additions: number,
	deletions: number,
	hunks: AiEditDiffHunkPayload[],
};

export type AiEditGetDiffRequest = {
	taskId: string,
	path: string,
};

export type AiEditListTimelinePayload = {
	entries: AiEditTimelineEntryPayload[],
};

export type AiEditListTimelineRequest = {
	taskId: string | null,
	limit: number | null,
};

export type AiEditOperationPayload = {
	id: string,
	taskId: string,
	turnId: string,
	/**  已知值："modify"。 */
	kind: string,
	path: string,
	newPath: string | null,
	sourceSnapshotId: string | null,
	beforeHash: string | null,
	afterHash: string | null,
	bytesBefore: number | null,
	bytesAfter: number | null,
	appliedAt: string,
	reason: string,
	toolCallId: string | null,
	diffText: string | null,
	pinned: boolean,
};

export type AiEditRestoreSnapshotPayload = {
	snapshotId: string,
	restoredFiles: string[],
	preRevertSnapshot: AiSnapshotPayload,
	restoredSnapshot: AiSnapshotPayload,
};

export type AiEditRestoreSnapshotRequest = {
	snapshotId: string,
};

export type AiEditRevertFilePayload = {
	taskId: string,
	path: string,
	operationId: string,
	restoredFiles: string[],
	preRevertSnapshot: AiSnapshotPayload,
	restoredSnapshot: AiSnapshotPayload,
};

export type AiEditRevertFileRequest = {
	taskId: string,
	path: string,
};

export type AiEditRevertHunkPayload = {
	taskId: string,
	path: string,
	operationId: string,
	hunkIndex: number,
	restoredFiles: string[],
	preRevertSnapshot: AiSnapshotPayload,
	restoredSnapshot: AiSnapshotPayload,
};

export type AiEditRevertHunkRequest = {
	taskId: string,
	path: string,
	hunkIndex: number,
};

export type AiEditRevertTaskPayload = {
	taskId: string,
	revertedOperationIds: string[],
	restoredFiles: string[],
	preRevertSnapshots: AiSnapshotPayload[],
	restoredSnapshots: AiSnapshotPayload[],
};

export type AiEditRevertTaskRequest = {
	taskId: string,
};

export type AiEditSetAuthLevelRequest = {
	/**  已知值："manual" | "per_task" | "session"。 */
	level: string,
	taskId: string | null,
};

export type AiEditSetPinPayload = {
	targetType: string,
	targetId: string,
	pinned: boolean,
	pinnedAt: string | null,
};

export type AiEditSetPinRequest = {
	/**  已知值："operation" | "snapshot" | "task"。 */
	targetType: string,
	targetId: string,
	pinned: boolean,
};

/**
 *  与前端 `aiEditTimelineEntrySchema` 一一对齐的判别联合，
 *  形如 `{ "type": "snapshot" | "operation", "data": { … } }`。
 */
export type AiEditTimelineEntryPayload = { type: "snapshot"; data: AiSnapshotPayload } | { type: "operation"; data: AiEditOperationPayload };

export type AiEditUndoOperationPayload = {
	operationId: string,
	restoredFiles: string[],
	preRevertSnapshot: AiSnapshotPayload,
	restoredSnapshot: AiSnapshotPayload,
};

export type AiEditUndoOperationRequest = {
	operationId: string,
};

export type AiInlineCompletionRangePayload = {
	startOffset: number,
	endOffset: number,
};

export type AiInlineCompletionRequest = {
	filePath: string,
	language: string,
	cursorOffset: number,
	prefix: string,
	suffix: string,
};

export type AiInlineCompletionResult = {
	insertText: string,
	range: AiInlineCompletionRangePayload,
	/**  置信度等级，已知值："low" | "medium" | "high"。 */
	confidence: string,
};

export type AiModelEndpointConfigPayload = {
	providerType: string,
	selectedModel: string | null,
	baseUrl: string | null,
	isBaseUrlConfigured: boolean,
	hasCredentials: boolean,
	isConfigured: boolean,
};

export type AiPatchFilePayload = {
	path: string,
	originalHash: string,
	/**
	 *  生成 patch 时源文件的 mtime（Unix epoch 毫秒）。
	 *  旧调用可为空；AED 写盘链路会在真正落盘前用运行时读取的 baseline 再做 OCC。
	 */
	originalModifiedAtMs?: number | null,
	hunks: AiPatchHunkPayload[],
};

export type AiPatchHunkPayload = {
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	/**
	 *  统一 diff hunk 的原始行序列。每行首字符约定为：
	 *  - `' '`（空格）：上下文行
	 *  - `'+'`：新增行
	 *  - `'-'`：删除行
	 *  - `"\\ No newline at end of file"`：标准 unified diff 无末尾换行标记
	 * 
	 *  普通行内不含末尾换行符；应用端按 unified diff 语义补齐。
	 */
	lines: string[],
};

export type AiPatchSetPayload = {
	summary: string,
	files: AiPatchFilePayload[],
};

export type AiProposePatchPayload = {
	patch: AiPatchSetPayload,
};

export type AiProposePatchRequest = {
	path: string,
	originalContent: string,
	updatedContent: string,
	summary: string,
};

export type AiProviderConnectionPayload = {
	config: AiConfigPayload,
	test: AiProviderTestPayload,
};

/**
 *  用于“测试连接 / 开始连接”的草稿配置。
 * 
 *  `api_key` 允许为空：为空时后端只会尝试读取当前 Provider 已保存的凭证；
 *  若也不存在已保存凭证，连接测试必须失败，不能伪造成功。
 */
export type AiProviderConnectionRequest = {
	role?: string | null,
	providerId?: string | null,
	providerType: string,
	selectedModel: string | null,
	baseUrl: string | null,
	inlineCompletionEnabled: boolean,
	chatEnabled: boolean,
	agentEnabled: boolean,
	apiKey: SecretString | null,
};

export type AiProviderTestPayload = {
	ok: boolean,
	/**  已知值："ok" | "unauthorized" | "rate-limited" | "network" | …。 */
	code: string,
	message: string,
};

/**
 *  ACP 反向 `session/request_permission` 的审批投递请求（契约层）。
 * 
 *  对齐 `acp::AcpRuntime::resolve_approval(session_id, tool_call_id, decision)`：
 *    * `session_id` / `tool_call_id` —— 定位挂起审批所属的会话与工具调用（ACP 原值，逐字透传）；
 *    * `decision` —— 选中项 `optionId`（ACP `RequestPermissionRequest.options[].optionId` 原值，
 *      逐字回填，绝不本地映射，对齐 `approval.rs` 的逐字匹配）。
 *  三者均必填且非空（前端总能从已渲染的审批气泡取得），空白校验由接线层负责。
 */
export type AiResolveApprovalRequest = {
	sessionId: string,
	toolCallId: string,
	decision: string,
};

export type AiSaveConfigRequest = {
	role?: string | null,
	providerType: string,
	selectedModel: string | null,
	baseUrl: string | null,
	inlineCompletionEnabled: boolean,
	chatEnabled: boolean,
	agentEnabled: boolean,
};

/**
 *  ⚠️ `api_key` 已包装在 `SecretString` 中，Debug 输出会被遮蔽为 `***`。
 *  调用方读取明文请使用 `request.api_key.expose()` 显式取出。
 */
export type AiSaveCredentialsRequest = {
	providerId: string,
	alias?: string | null,
	apiKey: SecretString,
};

export type AiSnapshotPayload = {
	id: string,
	/**
	 *  已知值："task-start" | "turn-start" | "pre-tool" | "manual"
	 *  | "pre-revert" | "revert"。
	 */
	scope: string,
	taskId: string,
	createdAt: string,
	label: string,
	fileRefs: string[],
	storageKey: string,
	sizeBytes: number,
	contentAvailable: boolean,
	pinned: boolean,
};

export type AiSuggestionPoolPayload = {
	suggestions: string[],
	model: string,
	generatedAt: string,
};

export type AiSuggestionPoolRequest = {
	count: number,
	locale: string,
	topics: string[],
};

export type AiWebFetchInput = {
	url: string,
	reason: string,
	maxBytes: number,
};

export type AiWebFetchPayload = {
	source: AiWebFetchResultPayload,
};

export type AiWebFetchResultPayload = {
	url: string,
	title: string,
	textRef: string,
	excerpt: string,
	bytes: number,
	fetchedAt: string,
	truncated: boolean,
};

export type AiWebSearchInput = {
	query: string,
	intent: string,
	maxResults: number,
	recency: string | null,
};

export type AiWebSearchPayload = {
	results: AiWebSearchResultPayload[],
};

export type AiWebSearchResultPayload = {
	title: string,
	url: string,
	snippet: string,
	sourceType: string,
	fetchedAt: string,
};

export type AnalyzeScriptPayload = {
	available: boolean,
	message: string | null,
	dialect: string,
	diagnostics: ScriptDiagnosticPayload[],
};

export type AnalyzeScriptRequest = {
	path: string | null,
	name: string | null,
	content: string,
};

export type CancelTerminalRunRequest = {
	runId: string,
	mode: string | null,
};

export type CloseTerminalSessionRequest = {
	sessionId: string,
};

/**  删除技能返回。 */
export type DeleteSkillPayload = {
	slug: string,
};

/**  删除技能入参。 */
export type DeleteSkillRequest = {
	slug: string,
};

export type DispatchTerminalScriptPayload = {
	sessionId: string,
	cwd: string,
	commandLine: string,
	usedTempFile: boolean,
	startedAt: string,
};

export type DispatchTerminalScriptRequest = {
	sessionId: string,
	path: string | null,
	workspaceRootPath: string | null,
	content: string,
	isDirty: boolean,
	runId: string,
};

export type DocumentEncoding = "utf-8" | "utf-8-bom" | "gbk" | "gb18030" | "utf-16le" | "utf-16be";

export type EnsureTerminalSessionRequest = {
	sessionId: string,
	cwd: string | null,
	cols: number,
	rows: number,
};

export type ExecutionEnvironment = {
	recommended: ExecutorKind,
	hasAny: boolean,
	executors: ExecutionOption[],
};

export type ExecutionOption = {
	type: ExecutorKind,
	label: string,
	available: boolean,
	description: string,
	commandPath: string | null,
};

export type ExecutorKind = "wsl";

export type FormatDocumentPayload = {
	/**  格式化后的全文；未命中可用 formatter 时原样回传入参 content。 */
	content: string,
	/**
	 *  实际使用的 formatter id（如 "shfmt" / "prettier" / "biome"）。
	 *  None 表示该语言无专用 External formatter 或未发现可用二进制，
	 *  前端据此退回 whitespace 归一。
	 */
	formatterId: string | null,
	lineCount: number,
	charCount: number,
};

export type FormatDocumentRequest = {
	/**  待格式化的全文。 */
	content: string,
	/**  由前端 resolveLanguageForPath 解析出的语言 id（如 "shell" / "typescript" / "python"）。 */
	languageId: string,
	/**  可选文件路径，供 formatter 选择 parser / 读取就近配置（如 prettier 按文件名）。 */
	path: string | null,
};

export type FormatScriptPayload = {
	content: string,
	encoding: DocumentEncoding,
	lineCount: number,
	charCount: number,
};

export type FormatScriptRequest = {
	path: string | null,
	content: string,
	/**  文本编码，已知值："utf-8" | "utf-8-bom" | "gbk" | …。 */
	encoding: DocumentEncoding,
};

/**  单条文件系统变更 */
export type FsChange = {
	/**  变更路径的绝对路径（已 canonicalize；Windows 上不含 `\\?\` UNC 前缀） */
	path: string,
	/**  事件类型 */
	kind: FsChangeKind,
};

/**  文件系统变更类型 */
export type FsChangeKind = "created" | "modified" | "removed" | "renamed";

export type GitBranchCheckoutRequest = {
	repositoryRootPath: string,
	branchName: string,
};

export type GitBranchCreateRequest = {
	repositoryRootPath: string,
	branchName: string,
	checkout: boolean,
};

export type GitBranchListPayload = {
	branches: GitBranchPayload[],
};

export type GitBranchPayload = {
	name: string,
	shorthand: string,
	kind: string,
	upstreamName: string | null,
	isCurrent: boolean,
	isHead: boolean,
	ahead: number,
	behind: number,
	lastCommit: GitCommitSummaryPayload | null,
};

export type GitCommitCheckoutRequest = {
	repositoryRootPath: string,
	commitId: string,
};

export type GitCommitDetailPayload = {
	id: string,
	shortId: string,
	summary: string,
	body: string,
	authorName: string,
	authorEmail: string,
	authoredAt: string,
	parentIds: string[],
	refs: GitCommitRefPayload[],
	fileCount: number,
	additions: number,
	deletions: number,
	files: GitCommitFileChangePayload[],
};

export type GitCommitDetailRequest = {
	repositoryRootPath: string,
	commitId: string,
};

export type GitCommitFileChangePayload = {
	relativePath: string,
	fileName: string,
	previousRelativePath: string | null,
	status: string,
	additions: number,
	deletions: number,
};

export type GitCommitFileDiffPayload = {
	relativePath: string,
	fileName: string,
	title: string,
	hunks: GitDiffHunk[],
	isBinary: boolean,
	isEmpty: boolean,
};

export type GitCommitFileDiffRequest = {
	repositoryRootPath: string,
	commitId: string,
	relativePath: string,
};

export type GitCommitHistoryPayload = {
	entries: GitCommitSummaryPayload[],
	hasMore: boolean,
	nextOffset: number | null,
};

export type GitCommitHistoryRequest = {
	repositoryRootPath: string,
	offset: number | null,
	limit: number | null,
};

export type GitCommitRefPayload = {
	name: string,
	kind: string,
	isHead: boolean,
};

export type GitCommitRequest = {
	repositoryRootPath: string,
	message: string,
	paths: string[],
};

export type GitCommitResultPayload = {
	status: GitRepositoryStatusPayload,
	commitId: string | null,
};

export type GitCommitRevertRequest = {
	repositoryRootPath: string,
	commitId: string,
};

export type GitCommitSummaryPayload = {
	id: string,
	shortId: string,
	summary: string,
	authorName: string,
	authorEmail: string,
	authoredAt: string,
	parentIds: string[],
	refs: GitCommitRefPayload[],
};

export type GitDiffHunk = {
	oldStart: number,
	oldCount: number,
	newStart: number,
	newCount: number,
	lines: GitDiffLine[],
};

export type GitDiffLine = {
	tag: string,
	oldLine: number | null,
	newLine: number | null,
	content: string,
};

export type GitDiffPreviewPayload = {
	id: string,
	repositoryRootPath: string,
	path: string,
	relativePath: string,
	title: string,
	mode: string,
	originalContent: string,
	modifiedContent: string,
	isEmpty: boolean,
};

export type GitDiffPreviewRequest = {
	repositoryRootPath: string,
	path: string,
	mode: string,
};

export type GitFileBaselinePayload = {
	available: boolean,
	message: string | null,
	repositoryRootPath: string | null,
	filePath: string,
	relativePath: string | null,
	isTracked: boolean,
	content: string | null,
};

export type GitFileStatusPayload = {
	path: string,
	relativePath: string,
	fileName: string,
	previousPath: string | null,
	previousRelativePath: string | null,
	indexStatus: string | null,
	worktreeStatus: string | null,
	isConflicted: boolean,
	isUntracked: boolean,
};

export type GitHubAuthRequest = {
	repositoryRootPath: string,
};

export type GitHubAuthStatusPayload = {
	authenticated: boolean,
	login: string | null,
	name: string | null,
	avatarUrl: string | null,
	htmlUrl: string | null,
	email: string | null,
	source: string | null,
	message: string | null,
};

export type GitHubBrowserAuthCompleteRequest = {
	repositoryRootPath: string,
	state: string,
};

export type GitHubBrowserAuthPayload = {
	authorizationUrl: string,
	state: string,
	expiresIn: number,
};

export type GitPathOperationRequest = {
	repositoryRootPath: string,
	paths: string[],
};

export type GitPullRequestCloseRequest = {
	repositoryRootPath: string,
	number: number,
};

export type GitPullRequestCreateRequest = {
	repositoryRootPath: string,
	title: string,
	body: string | null,
	base: string,
	head: string,
	draft: boolean | null,
};

export type GitPullRequestDetailPayload = {
	number: number,
	title: string,
	state: string,
	isDraft: boolean,
	author: string | null,
	headRef: string,
	baseRef: string,
	htmlUrl: string,
	createdAt: string,
	updatedAt: string,
	body: string,
	comments: number | null,
	additions: number | null,
	deletions: number | null,
	changedFiles: number | null,
	mergeable: boolean | null,
	mergeableState: string | null,
};

export type GitPullRequestDetailRequest = {
	repositoryRootPath: string,
	number: number,
};

export type GitPullRequestListRequest = {
	repositoryRootPath: string,
	state: string | null,
};

export type GitPullRequestMergeRequest = {
	repositoryRootPath: string,
	number: number,
	mergeMethod: string | null,
};

export type GitPullRequestSummaryPayload = {
	number: number,
	title: string,
	state: string,
	isDraft: boolean,
	author: string | null,
	headRef: string,
	baseRef: string,
	htmlUrl: string,
	createdAt: string,
	updatedAt: string,
	comments: number | null,
};

export type GitPullRequestSupportPayload = {
	available: boolean,
	remoteName: string | null,
	provider: string,
	repositoryUrl: string | null,
	pullRequestsUrl: string | null,
	createPullRequestUrl: string | null,
};

export type GitRemoteSetRequest = {
	repositoryRootPath: string,
	remoteName: string,
	remoteUrl: string,
};

export type GitRepositoryRootRequest = {
	repositoryRootPath: string,
};

export type GitRepositoryStatusPayload = {
	available: boolean,
	message: string | null,
	repositoryRootPath: string | null,
	repositoryName: string | null,
	gitDirPath: string | null,
	headBranchName: string | null,
	headShortName: string | null,
	headShortOid: string | null,
	isDetached: boolean,
	isClean: boolean,
	ahead: number,
	behind: number,
	stagedCount: number,
	unstagedCount: number,
	untrackedCount: number,
	conflictedCount: number,
	files: GitFileStatusPayload[],
	lastCommit: GitCommitSummaryPayload | null,
};

export type GitStashApplyRequest = {
	repositoryRootPath: string,
	stashIndex: number,
	pop: boolean,
};

export type GitStashDropRequest = {
	repositoryRootPath: string,
	stashIndex: number,
};

export type GitStashEntryPayload = {
	index: number,
	stashId: string,
	summary: string,
	branchName: string | null,
	commitShortId: string | null,
	createdAt: string,
	fileCount: number,
	additions: number,
	deletions: number,
	files: GitStashFilePayload[],
};

export type GitStashFilePayload = {
	relativePath: string,
	fileName: string,
	previousRelativePath: string | null,
	status: string,
	additions: number,
	deletions: number,
};

export type GitStashListPayload = {
	entries: GitStashEntryPayload[],
};

export type GitStashSaveRequest = {
	repositoryRootPath: string,
	message: string | null,
	includeUntracked: boolean,
};

export type ImageAssetPayload = {
	path: string,
	name: string,
	mimeType: string,
	byteSize: number,
};

export type LspCompletionItem = {
	label: string,
	insertText: string | null,
	kind: number | null,
	detail: string | null,
	documentation: string | null,
};

export type LspContentChange = LspContentChange_Serialize | LspContentChange_Deserialize;

export type LspContentChange_Deserialize = {
	range: LspRange | null,
	rangeLength: number | null,
	text: string,
};

export type LspContentChange_Serialize = {
	range?: LspRange | null,
	rangeLength?: number | null,
	text: string,
};

export type LspHoverResult = {
	contents: string,
};

export type LspPosition = {
	line: number,
	character: number,
};

export type LspRange = {
	start: LspPosition,
	end: LspPosition,
};

export type SaveScriptRequest = {
	path: string,
	content: string,
	/**
	 *  若来自工作区文件树 / 会话恢复 / 工作区批处理，必须传入工作区根并由后端校验路径边界。
	 *  通过系统文件选择器打开或另存为的单文件可为空，保留用户显式选择任意本地文件的能力。
	 */
	workspaceRootPath: string | null,
	/**  文本编码，已知值："utf-8" | "utf-8-bom" | "gbk" | …（保持字符串以便扩展）。 */
	encoding: DocumentEncoding,
};

/**  新建 / 更新技能入参。 */
export type SaveSkillRequest = {
	/**  None 表示新建（按名称生成 slug）；Some(slug) 表示更新已存在技能。 */
	slug: string | null,
	name: string,
	description: string,
	content: string,
};

export type ScriptDiagnosticPayload = {
	line: number,
	endLine: number,
	column: number,
	endColumn: number,
	level: ScriptDiagnosticSeverity,
	code: string,
	message: string,
};

export type ScriptDiagnosticSeverity = "error" | "warning" | "info" | "style";

export type ScriptFilePayload = {
	path: string,
	name: string,
	content: string,
	encoding: DocumentEncoding,
	lineCount: number,
	charCount: number,
};

export type SecretString = string;

export type SetWindowBackgroundInput = {
	label?: string | null,
	r: number,
	g: number,
	b: number,
	a?: number,
};

/**  单个技能详情（含正文，用于查看 / 编辑）。 */
export type SkillDetailPayload = {
	slug: string,
	name: string,
	description: string,
	content: string,
	path: string,
	updatedAtMs: number | null,
};

/**  技能列表整体返回（含技能根目录，便于前端提示存储位置）。 */
export type SkillListPayload = {
	rootPath: string,
	skills: SkillSummaryPayload[],
};

/**  技能列表项（轻量，仅含展示所需字段）。 */
export type SkillSummaryPayload = {
	slug: string,
	name: string,
	description: string,
	updatedAtMs: number | null,
};

export type SshConfigHostPayload = {
	id: string,
	name: string,
	username: string,
	host: string,
	port: number,
	identityPath: string | null,
	lastUsedLabel: string,
};

export type SshConnectionTestPayload = {
	ok: boolean,
	/**  已知值："ok" | "auth-failed" | "host-unreachable" | "timeout" | …。 */
	code: string,
	message: string,
};

export type SshConnectionTestRequest = {
	host: string,
	port: number,
	username: string,
	/**  已知值："password" | "key" | "agent"。 */
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
};

export type SshDirectoryCreatePayload = {
	remotePath: string,
};

export type SshDirectoryCreateRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remoteDirectory: string,
};

export type SshDirectoryEntryPayload = {
	name: string,
	path: string,
	/**  已知值："file" | "directory" | "symlink"。 */
	kind: string,
	size: number,
};

export type SshDirectoryListPayload = {
	path: string,
	entries: SshDirectoryEntryPayload[],
};

export type SshDirectoryListRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	path: string,
};

export type SshFileDownloadPayload = {
	remotePath: string,
	localPath: string,
	byteSize: number,
};

export type SshFileDownloadRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remotePath: string,
	localPath: string,
};

export type SshFileReadPayload = {
	remotePath: string,
	content: string,
	byteSize: number,
	encoding: string,
	lineCount: number,
	lineEnding: string,
	permission: string,
	owner: string,
	modifiedAt: string | null,
};

export type SshFileReadRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remotePath: string,
};

export type SshFileUploadPayload = {
	localPath: string,
	remotePath: string,
	byteSize: number,
};

export type SshFileUploadRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	localPath: string,
	remoteDirectory: string,
};

export type SshFileWritePayload = {
	remotePath: string,
	byteSize: number,
};

export type SshFileWriteRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remotePath: string,
	content: string,
	encoding: string,
	lineEnding: string,
};

export type SshHostKeyTrustPayload = {
	trusted: boolean,
};

export type SshPasswordGetRequest = {
	host: string,
	port: number,
	username: string,
};

export type SshPasswordPayload = {
	password: string,
};

export type SshPasswordSaveRequest = {
	host: string,
	port: number,
	username: string,
	password: SecretString,
};

export type SshPasswordStatusPayload = {
	hasPassword: boolean,
};

export type SshPathDeletePayload = {
	remotePath: string,
};

export type SshPathDeleteRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remotePath: string,
};

export type SshPathRenamePayload = {
	oldPath: string,
	newPath: string,
};

export type SshPathRenameRequest = {
	host: string,
	port: number,
	username: string,
	authMode: string,
	identityPath: string | null,
	password: SecretString | null,
	remotePath: string,
	newName: string,
};

export type TerminalInputRequest = {
	sessionId: string,
	data: string,
};

export type TerminalResizeRequest = {
	sessionId: string,
	cols: number,
	rows: number,
};

export type TerminalSessionPayload = {
	sessionId: string,
	cwd: string,
	shellLabel: string,
	created: boolean,
	initialOutput: string | null,
};

export type WindowStage = "main";

export type WorkspaceDirectoryPayload = {
	rootPath: string,
	rootName: string,
	entries: WorkspaceEntry[],
};

export type WorkspaceEntry = {
	path: string,
	name: string,
	/**  已知值："file" | "directory" | "symlink" | …。 */
	kind: WorkspacePathKind,
	hasChildren: boolean,
};

/**
 *  工作区文件系统事件
 * 
 *  derive `tauri_specta::Event` 让此类型同时：
 *  - 出现在生成的 TS 绑定 `events.workspaceFsEvent.listen(...)` 中
 *  - 提供类型化的 `.emit(app)` 方法（事件名自动为 `workspace-fs-event`）
 */
export type WorkspaceFsEvent = {
	/**
	 *  本批次的变更列表
	 * 
	 *  已按路径去重，同一路径保留 severity 最高的 kind
	 *  (Removed > Renamed > Created > Modified)
	 */
	changes: FsChange[],
	/**  监听根目录的绝对路径 */
	rootPath: string,
};

export type WorkspacePathCreatePayload = {
	path: string,
	name: string,
	kind: WorkspacePathKind,
};

export type WorkspacePathCreateRequest = {
	parentPath: string,
	rootPath: string,
	name: string,
	/**  已知值："file" | "directory"。 */
	kind: WorkspacePathKind,
};

export type WorkspacePathDeletePayload = {
	path: string,
};

export type WorkspacePathDeleteRequest = {
	path: string,
	rootPath: string,
};

export type WorkspacePathKind = "directory" | "file";

export type WorkspacePathRenamePayload = {
	oldPath: string,
	newPath: string,
	name: string,
};

export type WorkspacePathRenameRequest = {
	path: string,
	rootPath: string,
	newName: string,
};

export type WorkspaceReplacementAppliedFile = {
	path: string,
	relativePath: string,
	replacementCount: number,
	byteSize: number,
};

export type WorkspaceReplacementApplyPayload = {
	rootPath: string,
	changedFileCount: number,
	replacementCount: number,
	files: WorkspaceReplacementAppliedFile[],
};

export type WorkspaceReplacementApplyRequest = {
	request: WorkspaceReplacementRequest,
	expectedFiles: WorkspaceReplacementExpectedFile[],
};

export type WorkspaceReplacementExpectedFile = {
	path: string,
	beforeHash: string,
	includedMatchIds?: string[],
};

export type WorkspaceReplacementFilePreview = {
	path: string,
	relativePath: string,
	replacementCount: number,
	beforeHash: string,
	afterHash: string,
	diff: string,
	diffTruncated: boolean,
	linePreviews: WorkspaceReplacementLinePreview[],
};

export type WorkspaceReplacementLinePreview = {
	id: string,
	lineNumber: number,
	/**  命中所在行（已去掉行首缩进、未拼省略号）。 */
	beforeLine: string,
	/**  替换文本（前端据此构建 after 段与新增 diff）。 */
	insertedText: string,
	/**  命中区间在 before_line 中的起止（UTF-16 code unit 偏移）。 */
	matchStart: number,
	matchEnd: number,
	/**  仅当超过安全上限、对应一侧有内容被丢弃时为真（前端据此渲染数据级省略号）。 */
	truncatedStart: boolean,
	truncatedEnd: boolean,
	replacementCount: number,
};

export type WorkspaceReplacementPreviewPayload = {
	rootPath: string,
	fileCount: number,
	replacementCount: number,
	files: WorkspaceReplacementFilePreview[],
};

export type WorkspaceReplacementRequest = {
	workspaceRootPath: string,
	query: string,
	replacement: string,
	matchCase: boolean,
	wholeWord: boolean,
	useRegex: boolean,
	useStructural?: boolean,
	includePatterns?: string[],
	excludePatterns?: string[],
	limit: number | null,
};

export type WorkspaceSearchPayload = {
	rootPath: string,
	scannedFileCount: number,
	results: WorkspaceSearchResult[],
};

export type WorkspaceSearchRequest = {
	workspaceRootPath: string,
	query: string,
	scope: WorkspaceSearchScope,
	matchCase: boolean,
	wholeWord: boolean,
	useRegex: boolean,
	useStructural?: boolean,
	contentFuzzy?: boolean,
	includePatterns?: string[],
	excludePatterns?: string[],
	limit: number | null,
	streamToken?: number | null,
};

export type WorkspaceSearchResult = {
	path: string,
	relativePath: string,
	name: string,
	kind: WorkspaceSearchResultKind,
	lineNumber: number | null,
	lineText: string | null,
	matchStart: number | null,
	matchEnd: number | null,
	score: number,
};

export type WorkspaceSearchResultKind = "file-name" | "content" | "symbol";

export type WorkspaceSearchScope = "all" | "file-name" | "symbol" | "content";

/**
 *  内容搜索流式推送事件。
 * 
 *  仿照 workspace_watcher::WorkspaceFsEvent，通过官方 derive tauri_specta::Event 让该类型
 *  既出现在生成的 TS 绑定 events.workspaceSearchStreamEvent 中，又提供类型化的 .emit(app)。
 *  派生宏默认把 NAME 取为结构体名的 kebab-case，即 workspace-search-stream。
 */
export type WorkspaceSearchStreamEvent = {
	/**  关联的请求标识，对应 WorkspaceSearchRequest.stream_token；前端据此对账当前在途搜索。 */
	searchId: number,
	/**  解析后的工作区根目录绝对路径。 */
	rootPath: string,
	/**  本批次的内容命中（按发现顺序，未做全局排序）。 */
	results: WorkspaceSearchResult[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

