// 由 scripts/codemod-iconify-phase2.mjs 生成,请勿手改。

import {
  Activity,
  AlertTriangle,
  ArrowDownAZ,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpAZ,
  ArrowUpDown,
  Asterisk,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  BellRing,
  BookOpen,
  Braces,
  Brackets,
  Brain,
  Brush,
  Bug,
  Calendar,
  CalendarClock,
  CalendarMinus,
  ChartBar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleSlash,
  Clock,
  Clock3,
  Cloud,
  CodeXml,
  Coffee,
  Combine,
  Cone,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  Equal,
  EyeOff,
  File,
  FileCheck,
  FileClock,
  FileCode,
  FileCode2,
  FileDigit,
  FileMinus,
  FilePenLine,
  FilePlus,
  FileSearch,
  FileSymlink,
  Files,
  FileText,
  FileX,
  Filter,
  Flag,
  Folder,
  FolderTree,
  FolderX,
  GitBranch,
  GitBranchPlus,
  GitCommitHorizontal,
  GitFork,
  Globe,
  Grid3x3,
  HardDrive,
  Hash,
  HelpCircle,
  Image,
  Info,
  Key,
  Layers,
  List,
  ListOrdered,
  ListTodo,
  ListTree,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  MessageSquare,
  Monitor,
  MousePointer,
  Music2,
  NotebookPen,
  OctagonAlert,
  Package,
  Paperclip,
  Pencil,
  Play,
  Plug,
  RefreshCw,
  Repeat,
  Replace,
  Rocket,
  RotateCw,
  Ruler,
  Save,
  Scissors,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Skull,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  Tag,
  Terminal,
  TestTube,
  TextCursorInput,
  TimerOff,
  Trash2,
  Type,
  Undo2,
  UserCheck,
  Video,
  Webhook,
  Workflow,
  X,
} from '@lucide/vue';
import type { Component } from 'vue';
import GithubIcon from './GithubIcon.vue';

export const lucideIconRegistry = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-a-z': ArrowUpAZ,
  'arrow-up-down': ArrowUpDown,
  asterisk: Asterisk,
  'at-sign': AtSign,
  'badge-check': BadgeCheck,
  ban: Ban,
  bell: Bell,
  'bell-ring': BellRing,
  'book-open': BookOpen,
  braces: Braces,
  brackets: Brackets,
  brain: Brain,
  brush: Brush,
  bug: Bug,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-minus': CalendarMinus,
  'chart-bar': ChartBar,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-slash': CircleSlash,
  clock: Clock,
  'clock-3': Clock3,
  cloud: Cloud,
  'code-xml': CodeXml,
  coffee: Coffee,
  combine: Combine,
  cone: Cone,
  copy: Copy,
  'corner-down-left': CornerDownLeft,
  cpu: Cpu,
  database: Database,
  equal: Equal,
  'eye-off': EyeOff,
  file: File,
  'file-check': FileCheck,
  'file-clock': FileClock,
  'file-code': FileCode,
  'file-code-2': FileCode2,
  'file-digit': FileDigit,
  'file-minus': FileMinus,
  'file-pen-line': FilePenLine,
  'file-plus': FilePlus,
  'file-search': FileSearch,
  'file-symlink': FileSymlink,
  'file-text': FileText,
  'file-x': FileX,
  files: Files,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  'folder-tree': FolderTree,
  'folder-x': FolderX,
  'git-branch': GitBranch,
  'git-branch-plus': GitBranchPlus,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-fork': GitFork,
  github: Github,
  globe: Globe,
  'grid-3x3': Grid3x3,
  'hard-drive': HardDrive,
  hash: Hash,
  'help-circle': HelpCircle,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  list: List,
  'list-ordered': ListOrdered,
  'list-todo': ListTodo,
  'list-tree': ListTree,
  loader: Loader,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  monitor: Monitor,
  'mouse-pointer': MousePointer,
  'music-2': Music2,
  'notebook-pen': NotebookPen,
  'octagon-alert': OctagonAlert,
  package: Package,
  paperclip: Paperclip,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  replace: Replace,
  rocket: Rocket,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  save: Save,
  scissors: Scissors,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  skull: Skull,
  sparkles: Sparkles,
  square: Square,
  'square-terminal': SquareTerminal,
  star: Star,
  tag: Tag,
  terminal: Terminal,
  'test-tube': TestTube,
  'text-cursor-input': TextCursorInput,
  'timer-off': TimerOff,
  'trash-2': Trash2,
  type: Type,
  'undo-2': Undo2,
  'user-check': UserCheck,
  video: Video,
  webhook: Webhook,
  workflow: Workflow,
  x: X,
} satisfies Record<string, Component>;

export type TLucideIconName = keyof typeof lucideIconRegistry;
