// Auto-generated by scripts/fix-vapor-vitest-bridge-and-boundary.mjs
// Vue 3.6 beta Vapor runtime exports used by local experiment.

import type { App, Plugin } from 'vue';

declare module 'vue' {
  export const defineVaporComponent: (...args: unknown[]) => unknown;
  export const defineVaporAsyncComponent: (...args: unknown[]) => unknown;
  export const createVaporApp: (...args: unknown[]) => App;
  export const vaporInteropPlugin: Plugin;
}
