#!/usr/bin/env node
// scripts/acp-slice-3.mjs
// Hardened ACP Slice 3 frontend codemod (regenerated byte-exact against HEAD e67a2ef).
// 全有或全无:先在内存校验所有锚点,全部通过才落盘。
//   node scripts/acp-slice-3.mjs --check   # 干跑,不写
//   node scripts/acp-slice-3.mjs           # 应用
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const CHECK_ONLY = process.argv.includes('--check');
const normalizeEol = (s) => s.replace(/\r\n/g, '\n');
const countOccurrences = (hay, needle) => {
  let n = 0;
  let i = 0;
  for (;;) {
    const idx = hay.indexOf(needle, i);
    if (idx === -1) break;
    n += 1;
    i = idx + needle.length;
  }
  return n;
};

const FILES = [
  {
    file: 'src/types/ai/schema.ts',
    edits: [
      {
        find: `export const aiChatStreamPayloadSchema = z.object({
  streamId: z.string().min(1),
  assistantMessageId: z.string().min(1),
  providerType: aiProviderTypeSchema,
  model: z.string().min(1),
});`,
        replace: `export const aiChatStreamPayloadSchema = z.object({
  streamId: z.string().min(1),
  assistantMessageId: z.string().min(1),
  providerType: aiProviderTypeSchema,
  model: z.string().min(1),
  sessionId: z.string().min(1).nullable().optional(),
});`,
      },
    ],
  },
  {
    file: 'src/types/ai/index.ts',
    edits: [
      {
        find: `export interface IAiCancelRequest {
  streamId: string;
}`,
        replace: `export interface IAiCancelRequest {
  streamId: string;
  threadId: string | null;
}`,
      },
    ],
  },
  {
    file: 'src/services/ipc/ai.service.ts',
    edits: [
      {
        find: `  IAiApplyPatchRequest,
  IAiChatRequest,`,
        replace: `  IAiApplyPatchRequest,
  IAiCancelRequest,
  IAiChatRequest,`,
      },
      {
        find: `  cancel(payload: { streamId: string }): Promise<void> {
    return tauriService.aiCancel(payload);
  },`,
        replace: `  cancel(payload: IAiCancelRequest): Promise<void> {
    return tauriService.aiCancel(payload);
  },`,
      },
    ],
  },
  {
    file: 'src/composables/ai/sidecar-stream-listener.ts',
    edits: [
      {
        find: `    onEvent(payload.event);
  });`,
        replace: `    onEvent(payload.event);
  });

/**
 * 在已知 sessionId 之前就订阅 sidecar 流:先缓冲全部帧,bind(sessionId) 后回放匹配帧
 * 并继续转发后续匹配帧。用于消除「先订阅 → 再拿到 sessionId」之间的竞态窗口(零竞态)。
 */
export interface IBufferedSidecarSessionStream {
  bind(sessionId: string): void;
  dispose(): void;
}

export const subscribeSidecarStreamWithPrebuffer = async (
  onEvent: (event: TAgentUiEvent) => void,
): Promise<IBufferedSidecarSessionStream> => {
  const buffered: Array<{ sessionId: string; event: TAgentUiEvent }> = [];
  let boundSessionId: string | null = null;

  const unlisten = await aiService.onSidecarStream((payload) => {
    if (boundSessionId === null) {
      buffered.push({ sessionId: payload.sessionId, event: payload.event });
      return;
    }

    if (payload.sessionId !== boundSessionId) {
      return;
    }

    onEvent(payload.event);
  });

  return {
    bind(sessionId: string): void {
      if (boundSessionId !== null) {
        return;
      }

      boundSessionId = sessionId;

      for (const frame of buffered.splice(0)) {
        if (frame.sessionId === sessionId) {
          onEvent(frame.event);
        }
      }
    },
    dispose(): void {
      buffered.length = 0;
      unlisten();
    },
  };
};`,
      },
    ],
  },
  {
    file: 'src/composables/ai/useAiAssistant.ts',
    edits: [
      {
        find: `} from './useAiAssistant.stream';
import { createStreamPipeline } from './useAiAssistant.stream-pipeline';

type TAiQuickActionId`,
        replace: `} from './useAiAssistant.stream';

type TAiQuickActionId`,
      },
      {
        find: `import { subscribeSidecarSessionStream } from '@/composables/ai/sidecar-stream-listener';`,
        replace: `import {
  subscribeSidecarSessionStream,
  subscribeSidecarStreamWithPrebuffer,
} from '@/composables/ai/sidecar-stream-listener';`,
      },
      {
        find: `  const executeAiRequest = async (
    requestMessages: IAiChatMessage[],
    visibleMessages: IAiChatMessage[],
    references: IAiContextReference[],
    threadId: string | null,
  ): Promise<void> => {
    errorMessage.value = '';
    isSending.value = true;
    activeBufferedThreadId.value = threadId;

    const assistantMessage: IAiChatMessage = {
      id: createMessageId('assistant'),
      role: 'assistant',
      content: '',
      createdAt: new Date().toISOString(),
      references: [],
      stream: {
        status: 'streaming',
      },
    };

    activeAssistantMessage.value = assistantMessage;
    activeAssistantBaseMessages.value = visibleMessages;
    messages.value = [...visibleMessages, assistantMessage];

    let unlisten: (() => void) | null = null;
    let hasSettledStream = false;

    const settle = (): void => {
      hasSettledStream = true;
      activeStreamResolve.value?.();
    };

    const pipeline = createStreamPipeline(
      {
        aiStream,
        activeStreamId,
        errorMessage,
        syncActiveAssistantMessage,
        clearAttachedFiles,
      },
      assistantMessage,
      settle,
    );

    try {
      unlisten = await aiService.onChatStream(pipeline.handleEvent);

      const stream = await aiService.chatStream({
        threadId,
        messages: requestMessages,
        references,
      });

      pipeline.startAssistantStream(stream.streamId, stream.assistantMessageId);

      await new Promise<void>((resolve) => {
        if (hasSettledStream) {
          resolve();
          return;
        }

        activeStreamResolve.value = resolve;
      });
    } finally {
      pipeline.flushBufferedText();
      commitDisplayMessagesToStore(threadId);
      unlisten?.();

      activeStreamResolve.value = null;
      activeStreamId.value = null;
      activeAbortController.value = null;
      activeAssistantMessage.value = null;
      activeAssistantBaseMessages.value = [];
      clearActiveBufferedThread(threadId);
      isSending.value = false;
      syncDisplayMessagesFromActiveThread();
    }
  };`,
        replace: `  const executeAiRequest = async (
    requestMessages: IAiChatMessage[],
    visibleMessages: IAiChatMessage[],
    references: IAiContextReference[],
    threadId: string | null,
  ): Promise<void> => {
    errorMessage.value = '';
    isSending.value = true;
    activeBufferedThreadId.value = threadId;

    const assistantMessageId = createMessageId('assistant');
    const targetThreadId = threadId;
    const placeholderMessage: IAiChatMessage = {
      id: assistantMessageId,
      role: 'assistant',
      content: '',
      createdAt: new Date().toISOString(),
      references: [],
      stream: {
        status: 'streaming',
      },
    };

    activeAgentMessageId.value = assistantMessageId;
    messages.value = [...visibleMessages, placeholderMessage];
    commitDisplayMessagesToStore(targetThreadId);
    activeAbortController.value = new AbortController();

    let hasSettledStream = false;

    const settle = (): void => {
      hasSettledStream = true;
      activeStreamResolve.value?.();
    };

    const liveEventBuffer = createSidecarLiveEventBuffer((events) => {
      const { doneEvent, errorEvent } = getLatestSidecarLiveEvents(events);
      applySidecarLiveEventsToAgentMessage(assistantMessageId, targetThreadId, '', events);

      if (doneEvent || errorEvent) {
        settle();
      }
    });

    const sidecarStream = await subscribeSidecarStreamWithPrebuffer((event) => {
      liveEventBuffer.push(event);
    });

    try {
      const stream = await aiService.chatStream({
        threadId,
        messages: requestMessages,
        references,
      });

      if (!stream.sessionId) {
        throw new Error('AI 服务未返回 sessionId(需要启用 acp_client 后端)。');
      }

      activeStreamId.value = stream.streamId;
      sidecarStream.bind(stream.sessionId);

      await new Promise<void>((resolve) => {
        if (hasSettledStream) {
          resolve();
          return;
        }

        activeStreamResolve.value = resolve;
      });

      liveEventBuffer.flush();
    } catch (error) {
      if (activeAbortController.value?.signal.aborted) {
        disposeSidecarAnswerStream(assistantMessageId);
      } else {
        failSidecarAgentMessage(assistantMessageId, toErrorMessage(error, MSG_CALL_FAILED));
      }
    } finally {
      liveEventBuffer.dispose();
      sidecarStream.dispose();
      commitDisplayMessagesToStore(targetThreadId);

      activeStreamResolve.value = null;
      activeStreamId.value = null;
      activeAbortController.value = null;
      activeAgentMessageId.value = null;
      clearActiveBufferedThread(targetThreadId);
      isSending.value = false;
      syncDisplayMessagesFromActiveThread();
    }
  };`,
      },
      {
        find: `    if (streamId) {
      void aiService.cancel({ streamId });
    }`,
        replace: `    if (streamId) {
      void aiService.cancel({ streamId, threadId: targetThreadId ?? null });
    }`,
      },
    ],
  },
];

const root = process.cwd();
const failures = [];
const plans = [];

for (const entry of FILES) {
  const abs = resolve(root, entry.file);
  let raw;
  try {
    raw = readFileSync(abs, 'utf8');
  } catch (err) {
    failures.push(`${entry.file}: 无法读取 (${err.message})`);
    continue;
  }
  const usedCrlf = raw.includes('\r\n');
  let content = normalizeEol(raw);

  for (let i = 0; i < entry.edits.length; i += 1) {
    const edit = entry.edits[i];
    const find = normalizeEol(edit.find);
    const expected = edit.count ?? 1;
    const actual = countOccurrences(content, find);

    if (actual !== expected) {
      const firstLine = (find.split('\n').find((l) => l.trim() !== '') ?? '').trim();
      const lineHits = content.split('\n').filter((l) => l.includes(firstLine)).length;
      failures.push(
        `${entry.file} edit#${i + 1}: 期望 ${expected} 处匹配, 实际 ${actual} 处。` +
          ` 锚点首行【${firstLine}】在文件中出现 ${lineHits} 次` +
          `${lineHits > 0 ? '(说明是空白/缩进或邻近文本漂移)' : '(说明该段不在文件中)'}。`,
      );
      continue;
    }
    content = content.split(find).join(normalizeEol(edit.replace));
  }

  plans.push({ abs, file: entry.file, output: usedCrlf ? content.replace(/\n/g, '\r\n') : content });
}

if (failures.length > 0) {
  for (const f of failures) console.error(`✗ ${f}`);
  console.error('\n✗ 有锚点未匹配,未写入任何文件。');
  process.exit(1);
}

if (CHECK_ONLY) {
  for (const p of plans) console.log(`✓ ${p.file}: 全部锚点匹配通过(干跑,未写入)。`);
  console.log('\n✓ --check 通过,可去掉 --check 正式应用。');
  process.exit(0);
}

for (const p of plans) {
  writeFileSync(p.abs, p.output, 'utf8');
  console.log(`✓ 已写入 ${p.file}`);
}
console.log('\n✓ Slice 3 应用完成。');