use crate::commands::lsp::commands as lsp_commands;
use crate::commands::terminal::commands as terminal_commands;
use crate::commands::{
    builtin_agent, agent_webview, ai, format, git, script_run, search, shell_tools, skills, ssh,
    window, window_stage, workspace_fs, workspace_watcher,
};
use crate::launch;
use specta_typescript::Typescript;
use std::path::PathBuf;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands, collect_events};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .events(collect_events![
            workspace_watcher::WorkspaceFsEvent,
            search::WorkspaceSearchStreamEvent,
            agent_webview::AgentWebviewNavigatedEvent,
            agent_webview::AgentWebviewConsoleEvent,
            agent_webview::AgentWebviewElementPickedEvent,
        ])
        .commands(collect_commands![
            script_run::detect_execution_environment,
            search::apply_workspace_replacement,
            search::preview_workspace_replacement,
            search::search_workspace,
            shell_tools::format_script,
            format::format_document,
            skills::list_skills,
            skills::read_skill,
            skills::save_skill,
            skills::delete_skill,
            window_stage::apply_window_stage,
            window::set_window_background,
            workspace_fs::create_workspace_path,
            workspace_fs::delete_workspace_path,
            workspace_fs::list_workspace_entries,
            workspace_fs::load_image_asset,
            workspace_fs::load_script,
            workspace_fs::rename_workspace_path,
            workspace_fs::save_script,
            workspace_watcher::start_workspace_watching,
            workspace_watcher::stop_workspace_watching,
            terminal_commands::ensure_terminal_session,
            terminal_commands::write_terminal_input,
            terminal_commands::resize_terminal_session,
            terminal_commands::close_terminal_session,
            terminal_commands::dispatch_script_to_terminal,
            terminal_commands::cancel_terminal_run,
            terminal_commands::acknowledge_terminal_data,
            terminal_commands::heartbeat_terminal_session,
            git::branches::list_git_branches,
            git::branches::checkout_git_branch,
            git::branches::checkout_git_commit,
            git::branches::create_git_branch,
            git::diff::get_git_diff_preview,
            git::diff::get_git_commit_file_diff,
            git::diff::get_git_commit_file_diff_preview,
            git::github_auth::get_github_auth_status,
            git::github_auth::begin_github_browser_auth,
            git::github_auth::complete_github_browser_auth,
            git::github_auth::connect_github,
            git::github_auth::disconnect_github,
            git::history::list_git_commit_history,
            git::history::get_git_commit_detail,
            git::pull_request::get_git_pull_request_support,
            git::pull_request::set_git_remote,
            git::pull_request::list_git_pull_requests,
            git::pull_request::get_git_pull_request_detail,
            git::pull_request::create_git_pull_request,
            git::pull_request::merge_git_pull_request,
            git::pull_request::close_git_pull_request,
            git::revision::revert_git_commit,
            git::stash::list_git_stashes,
            git::stash::save_git_stash,
            git::stash::apply_git_stash,
            git::stash::drop_git_stash,
            git::status::get_git_repository_status,
            git::status::init_git_repository,
            git::status::get_git_file_baseline,
            git::status::stage_git_paths,
            git::status::unstage_git_paths,
            git::status::commit_git_index,
            git::status::discard_git_paths,
            ssh::connection::test_ssh_connection,
            ssh::connection::trust_ssh_host_key,
            ssh::credentials::save_ssh_password,
            ssh::credentials::get_ssh_password,
            ssh::config::list_ssh_config_hosts,
            ssh::transfer::list_ssh_directory,
            ssh::transfer::download_ssh_file,
            ssh::transfer::upload_ssh_file,
            ssh::transfer::read_ssh_file,
            ssh::transfer::write_ssh_file,
            ssh::transfer::delete_ssh_path,
            ssh::transfer::rename_ssh_path,
            ssh::transfer::create_ssh_directory,
            builtin_agent::builtin_agent_health,
            builtin_agent::builtin_agent_restart,
            builtin_agent::builtin_agent_warmup,
            builtin_agent::builtin_agent_external_chat,
            builtin_agent::builtin_agent_restore_checkpoint,
            agent_webview::agent_webview_create,
            agent_webview::agent_webview_set_bounds,
            agent_webview::agent_webview_set_visible,
            agent_webview::agent_webview_navigate,
            agent_webview::agent_webview_back,
            agent_webview::agent_webview_forward,
            agent_webview::agent_webview_reload,
            agent_webview::agent_webview_start_select,
            agent_webview::agent_webview_cancel_select,
            agent_webview::agent_webview_open_external,
            agent_webview::agent_webview_destroy,
            ai::gateway::ai_get_config,
            ai::gateway::ai_save_config,
            ai::gateway::ai_set_seeded_models,
            ai::gateway::ai_save_credentials,
            ai::gateway::ai_test_provider_config,
            ai::gateway::ai_connect_provider,
            ai::gateway::ai_clear_credentials,
            ai::gateway::ai_test_provider,
            ai::gateway::ai_generate_conversation_title,
            ai::gateway::ai_get_suggestion_pool_cache,
            ai::gateway::ai_generate_suggestion_pool,
            ai::gateway::ai_cancel,
            ai::gateway::ai_resolve_approval,
            ai::gateway::ai_set_session_config_option,
            ai::gateway::ai_ensure_acp_session,
            ai::gateway::ai_inline_complete,
            ai::agent::ai_agent_classify_task,
            ai::agent::ai_agent_set_network_permission,
            ai::tools::ai_web_search,
            ai::tools::ai_web_fetch,
            ai::edit::ai_propose_patch,
            ai::edit::ai_apply_patch,
            ai::edit::ai_edit_get_auth_level,
            ai::edit::ai_edit_set_auth_level,
            ai::edit::ai_edit_list_timeline,
            ai::edit::ai_edit_set_pin,
            ai::edit::ai_edit_get_diff,
            ai::edit::ai_edit_create_snapshot,
            ai::edit::ai_edit_restore_snapshot,
            ai::edit::ai_edit_undo_operation,
            ai::edit::ai_edit_revert_file,
            ai::edit::ai_edit_revert_hunk,
            ai::edit::ai_edit_revert_task,
            lsp_commands::lsp_start,
            lsp_commands::lsp_stop,
            lsp_commands::lsp_did_open,
            lsp_commands::lsp_did_change,
            lsp_commands::lsp_did_close,
            lsp_commands::lsp_completion,
            lsp_commands::lsp_hover,
            launch::drain_pending_open_files,
        ])
}

pub fn export(builder: &Builder<tauri::Wry>) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings/tauri.ts");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create tauri binding directory");
    }
    builder
        .export(Typescript::default(), path)
        .expect("failed to export tauri-specta TypeScript bindings");
}
